mod common;

#[cfg(test)]
mod tests {
    use super::common::{exec_sql, run_uvg, snapshot_dir, tmpdir};
    use std::path::PathBuf;

    #[tokio::test]
    async fn test_out_dir_first_run_then_noop() {
        let dir = tmpdir("outdir-first-then-noop");
        let source = dir.join("source.db");
        let target = dir.join("target.db");
        let migrations = dir.join("migrations");

        exec_sql(
            &source,
            "CREATE TABLE users(id INTEGER PRIMARY KEY, email TEXT NOT NULL);
             CREATE TABLE posts(id INTEGER PRIMARY KEY, user_id INTEGER, body TEXT,
                                FOREIGN KEY(user_id) REFERENCES users(id));",
        )
        .await;
        // Touch the target so the file exists. uvg still sees an empty
        // schema and emits CREATE TABLEs for every source table.
        exec_sql(
            &target,
            "CREATE TABLE _bootstrap(id INTEGER); DROP TABLE _bootstrap;",
        )
        .await;

        let src_url = format!("sqlite:///{}", source.display());
        let tgt_url = format!("sqlite:///{}", target.display());
        let mig_str = migrations.display().to_string();

        // First run - should produce per-table layout.
        let out = run_uvg(&[
            "--generator",
            "ddl",
            "--out-dir",
            &mig_str,
            "--name",
            "initial",
            &src_url,
            &tgt_url,
        ]);
        assert!(
            out.status.success(),
            "first run failed: {}",
            String::from_utf8_lossy(&out.stderr)
        );

        assert!(migrations.join("users").is_dir(), "users/ subdir missing");
        assert!(migrations.join("posts").is_dir(), "posts/ subdir missing");
        assert!(migrations.join("_runs").is_dir(), "_runs/ missing");

        // One .sql per table, and the manifest names both.
        let users_sql: Vec<_> = std::fs::read_dir(migrations.join("users"))
            .unwrap()
            .map(|e| e.unwrap().file_name().into_string().unwrap())
            .collect();
        assert_eq!(
            users_sql.len(),
            1,
            "expected one users sql, got {users_sql:?}"
        );
        assert!(users_sql[0].ends_with("__initial.sql"));

        let body = std::fs::read_to_string(migrations.join("users").join(&users_sql[0])).unwrap();
        assert!(
            body.contains("-- Generated by uvg"),
            "missing provenance header: {body}"
        );
        assert!(
            body.contains("CREATE TABLE \"users\""),
            "missing CREATE: {body}"
        );

        // Snapshot the directory before the second (no-op) run.
        // To make the no-op meaningful, apply the migrations to the
        // target first so the schemas match.
        let mut migration_files: Vec<PathBuf> = Vec::new();
        for sub in ["users", "posts"] {
            for entry in std::fs::read_dir(migrations.join(sub)).unwrap() {
                migration_files.push(entry.unwrap().path());
            }
        }
        migration_files.sort();
        for path in &migration_files {
            let sql = std::fs::read_to_string(path).unwrap();
            // Strip comment-only header lines (they aren't valid SQL inside
            // executescript on some SQLite builds; sqlx tolerates them but
            // we filter anyway for clarity).
            let stripped: String = sql
                .lines()
                .filter(|l| !l.trim_start().starts_with("--"))
                .collect::<Vec<_>>()
                .join("\n");
            exec_sql(&target, &stripped).await;
        }

        let before = snapshot_dir(&migrations);

        // Second run with identical source/target - must write nothing.
        let out2 = run_uvg(&[
            "--generator",
            "ddl",
            "--out-dir",
            &mig_str,
            "--name",
            "should-not-appear",
            &src_url,
            &tgt_url,
        ]);
        assert!(
            out2.status.success(),
            "noop run failed: {}",
            String::from_utf8_lossy(&out2.stderr)
        );
        let stderr = String::from_utf8_lossy(&out2.stderr);
        assert!(
            stderr.contains("no schema changes"),
            "expected no-op message, got: {stderr}"
        );

        let after = snapshot_dir(&migrations);
        assert_eq!(
            before, after,
            "no-op run must leave the out-dir byte-identical"
        );

        std::fs::remove_dir_all(&dir).ok();
    }

    #[tokio::test]
    async fn test_out_dir_requires_target_url() {
        let dir = tmpdir("outdir-no-target");
        let source = dir.join("source.db");
        let migrations = dir.join("migrations");

        exec_sql(&source, "CREATE TABLE users(id INTEGER PRIMARY KEY);").await;
        let src_url = format!("sqlite:///{}", source.display());
        let mig_str = migrations.display().to_string();

        // No target URL - uvg should refuse and explain.
        let out = run_uvg(&["--generator", "ddl", "--out-dir", &mig_str, &src_url]);
        assert!(!out.status.success(), "expected non-zero exit");
        let stderr = String::from_utf8_lossy(&out.stderr);
        assert!(
            stderr.contains("target database URL"),
            "expected helpful error about missing target URL, got: {stderr}"
        );
        assert!(
            !migrations.exists() || snapshot_dir(&migrations).is_empty(),
            "no files should be written when --out-dir is misconfigured"
        );

        std::fs::remove_dir_all(&dir).ok();
    }
}
