use std::collections::HashMap;

use crate::cli::DdlOptions;
use crate::codegen::{
    is_auto_increment_column, is_primary_key_column, is_unique_constraint_index, topo_sort_tables,
};
use crate::ddl_typemap;
use crate::dialect::Dialect;
use crate::schema::{
    ColumnInfo, ConstraintInfo, ConstraintType, IntrospectedSchema, TableInfo, TableType,
};

/// Output from DDL generation.
pub enum DdlOutput {
    Single(String),
    Split(Vec<(String, String)>),
}

pub struct DdlGenerator;

impl DdlGenerator {
    pub fn generate(
        &self,
        schema: &IntrospectedSchema,
        target_schema: Option<&IntrospectedSchema>,
        options: &DdlOptions,
    ) -> DdlOutput {
        match target_schema {
            Some(target) => {
                let ddl = super::ddl_diff::diff_schemas(schema, target, options);
                DdlOutput::Single(ddl)
            }
            None => self.generate_full(schema, options),
        }
    }

    fn generate_full(&self, schema: &IntrospectedSchema, options: &DdlOptions) -> DdlOutput {
        let source_dialect = schema.dialect;
        let target_dialect = options.target_dialect;
        let sorted = topo_sort_tables(&schema.tables);

        // Filter to tables only (skip views for DDL)
        let tables: Vec<&&TableInfo> = sorted
            .iter()
            .filter(|t| t.table_type == TableType::Table)
            .collect();

        let mut all_stmts: Vec<String> = Vec::new();
        let mut per_table: Vec<(String, String)> = Vec::new();

        // Detect circular FK dependencies — warn if cycles exist
        let has_cycles = detect_fk_cycles(&schema.tables);

        // Header
        let mut header =
            format!("-- Generated by uvg\n-- Source: {source_dialect}, Target: {target_dialect}\n");
        if has_cycles {
            header.push_str("-- WARNING: Circular foreign key dependencies detected.\n-- Some FK constraints may reference tables not yet created.\n-- Consider applying FK constraints separately via ALTER TABLE.\n");
        }

        // Enum types (PG target only)
        let enum_stmts = generate_enum_types(schema, target_dialect);

        for table in &tables {
            let mut table_stmts = Vec::new();

            let create = generate_create_table(table, source_dialect, target_dialect, options);
            table_stmts.push(create);

            if !options.noindexes {
                let indexes = generate_indexes(table, target_dialect);
                table_stmts.extend(indexes);
            }

            if !options.nocomments {
                let comments = generate_comments(table, target_dialect);
                table_stmts.extend(comments);
            }

            let table_ddl = table_stmts.join("\n\n");
            all_stmts.push(table_ddl.clone());
            // Disambiguate filenames by schema for multi-schema introspection
            let filename =
                if table.schema.is_empty() || table.schema == target_dialect.default_schema() {
                    format!("{}.sql", table.name)
                } else {
                    format!("{}_{}.sql", table.schema, table.name)
                };
            per_table.push((filename, table_ddl));
        }

        if options.split_tables {
            let mut files: Vec<(String, String)> = Vec::new();

            if !enum_stmts.is_empty() {
                files.push((
                    "_types.sql".to_string(),
                    format!("{header}\n{}", enum_stmts.join("\n\n")),
                ));
            }

            for (filename, content) in per_table {
                files.push((filename, format!("{header}\n{content}\n")));
            }

            // Order file uses the actual filenames from per_table (already schema-qualified)
            let order: Vec<String> = files
                .iter()
                .filter(|(n, _)| n != "_types.sql")
                .map(|(n, _)| n.clone())
                .collect();
            files.push(("_order.txt".to_string(), order.join("\n") + "\n"));

            DdlOutput::Split(files)
        } else {
            let mut full = header;
            if !enum_stmts.is_empty() {
                full.push('\n');
                full.push_str(&enum_stmts.join("\n\n"));
                full.push_str("\n\n");
            }
            full.push('\n');
            full.push_str(&all_stmts.join("\n\n"));
            full.push('\n');
            DdlOutput::Single(full)
        }
    }
}

/// Quote an identifier for the target dialect.
pub(super) fn quote_identifier(name: &str, dialect: Dialect) -> String {
    match dialect {
        Dialect::Postgres | Dialect::Sqlite => format!("\"{}\"", name.replace('"', "\"\"")),
        Dialect::Mysql => format!("`{}`", name.replace('`', "``")),
        Dialect::Mssql => format!("[{}]", name.replace(']', "]]")),
    }
}

/// Generate a CREATE TABLE statement.
pub(super) fn generate_create_table(
    table: &TableInfo,
    source_dialect: Dialect,
    target_dialect: Dialect,
    options: &DdlOptions,
) -> String {
    let qname = qualified_table_name(&table.schema, &table.name, target_dialect);
    let mut parts: Vec<String> = Vec::new();
    // Comments for CHECK constraints we dropped because their predicate
    // wasn't portable — kept separate from `parts` so they don't end up
    // on the comma-joined body (would produce trailing/double commas).
    // Emitted after the CREATE TABLE statement closes.
    let mut dropped_check_comments: Vec<String> = Vec::new();

    // Detect if any column has inline PK AUTOINCREMENT (SQLite)
    let has_inline_pk = target_dialect == Dialect::Sqlite
        && table.columns.iter().any(|col| {
            is_auto_increment_column(col, source_dialect)
                && is_primary_key_column(&col.name, &table.constraints)
        });

    // Columns
    for col in &table.columns {
        parts.push(generate_column_def(
            col,
            &table.constraints,
            source_dialect,
            target_dialect,
        ));
    }

    // Constraints
    if !options.noconstraints {
        // Primary key (suppress if SQLite auto-increment already emitted inline PK)
        if !has_inline_pk {
            for c in &table.constraints {
                if c.constraint_type == ConstraintType::PrimaryKey {
                    let cols: Vec<String> = c
                        .columns
                        .iter()
                        .map(|col| quote_identifier(col, target_dialect))
                        .collect();
                    parts.push(format!(
                        "    CONSTRAINT {} PRIMARY KEY ({})",
                        quote_identifier(&c.name, target_dialect),
                        cols.join(", ")
                    ));
                }
            }
        }

        // Unique constraints
        for c in &table.constraints {
            if c.constraint_type == ConstraintType::Unique {
                let cols: Vec<String> = c
                    .columns
                    .iter()
                    .map(|col| quote_identifier(col, target_dialect))
                    .collect();
                parts.push(format!(
                    "    CONSTRAINT {} UNIQUE ({})",
                    quote_identifier(&c.name, target_dialect),
                    cols.join(", ")
                ));
            }
        }

        // Foreign keys
        for c in &table.constraints {
            if c.constraint_type == ConstraintType::ForeignKey {
                if let Some(ref fk) = c.foreign_key {
                    let cols: Vec<String> = c
                        .columns
                        .iter()
                        .map(|col| quote_identifier(col, target_dialect))
                        .collect();
                    let ref_table =
                        qualified_table_name(&fk.ref_schema, &fk.ref_table, target_dialect);
                    let ref_cols: Vec<String> = fk
                        .ref_columns
                        .iter()
                        .map(|col| quote_identifier(col, target_dialect))
                        .collect();
                    let mut fk_str = format!(
                        "    CONSTRAINT {} FOREIGN KEY ({}) REFERENCES {} ({})",
                        quote_identifier(&c.name, target_dialect),
                        cols.join(", "),
                        ref_table,
                        ref_cols.join(", ")
                    );
                    if fk.delete_rule != "NO ACTION" {
                        fk_str.push_str(&format!(" ON DELETE {}", fk.delete_rule));
                    }
                    if fk.update_rule != "NO ACTION" {
                        fk_str.push_str(&format!(" ON UPDATE {}", fk.update_rule));
                    }
                    parts.push(fk_str);
                }
            }
        }

        // Check constraints. Predicate text is source-verbatim from
        // introspection. Identifier-quote translation (backticks → quotes,
        // brackets → quotes, PG ::casts stripped) is in
        // translate_check_predicate. Cross-dialect predicate-SEMANTICS
        // translation (regex → LIKE, ARRAY[...] → comma-separated lists,
        // PG operator classes → equivalent MSSQL/MySQL forms) is the
        // bigger AST-level problem called out in #33; out of scope here.
        //
        // For cross-dialect runs (source != target), we skip CHECK
        // constraints whose predicate contains tokens we know don't port —
        // emitting them would fail at apply time and abort the table.
        // Same-dialect runs always emit verbatim. The dropped predicate is
        // surfaced as a `-- ` comment so the user can hand-translate.
        //
        // Dropped-check comments go in a parallel vec rather than into
        // `parts`: `parts.join(",\n")` below would leave a trailing comma
        // before `)` if a `-- DROPPED ...` line were the last entry, or
        // produce two commas in a row mid-body. Comments don't get joined
        // with a comma — they're appended after the body close.
        for c in &table.constraints {
            if c.constraint_type == ConstraintType::Check {
                if let Some(ref expr) = c.check_expression {
                    if source_dialect != target_dialect
                        && !check_predicate_is_portable(expr, source_dialect, target_dialect)
                    {
                        dropped_check_comments.push(format!(
                            "-- DROPPED CHECK {}: predicate uses non-portable syntax\n--   source: {}",
                            c.name,
                            expr.replace('\n', " ")
                        ));
                        continue;
                    }
                    let translated_expr =
                        translate_check_predicate(expr, source_dialect, target_dialect);
                    parts.push(format!(
                        "    CONSTRAINT {} CHECK ({})",
                        quote_identifier(&c.name, target_dialect),
                        translated_expr
                    ));
                }
            }
        }
    }

    let body = parts.join(",\n");

    // MySQL table comment is inline
    let table_comment = if !options.nocomments && target_dialect == Dialect::Mysql {
        table
            .comment
            .as_ref()
            .map(|c| format!(" COMMENT '{}'", c.replace('\'', "''")))
            .unwrap_or_default()
    } else {
        String::new()
    };

    let mut output = format!("CREATE TABLE {qname} (\n{body}\n){table_comment};");
    if !dropped_check_comments.is_empty() {
        // Emit dropped-check comments after the CREATE TABLE — they're not
        // part of the statement body, just human-readable notes about
        // constraints uvg couldn't translate.
        output.push('\n');
        for comment in &dropped_check_comments {
            output.push_str(comment);
            output.push('\n');
        }
    }
    output
}

/// Generate a column definition line.
pub(super) fn generate_column_def(
    col: &ColumnInfo,
    constraints: &[ConstraintInfo],
    source_dialect: Dialect,
    target_dialect: Dialect,
) -> String {
    let qname = quote_identifier(&col.name, target_dialect);

    // Detect auto-increment
    let is_auto = is_auto_increment_column(col, source_dialect);

    let is_pk = is_primary_key_column(&col.name, constraints);

    // Compute canonical type once (used for type mapping and boolean default detection)
    let canonical = crate::ddl_typemap::to_canonical(col, source_dialect);
    let is_boolean = matches!(canonical, crate::ddl_typemap::CanonicalType::Boolean);

    // Type
    let type_str = if is_auto {
        format_autoincrement_type(col, source_dialect, target_dialect, is_pk)
    } else {
        ddl_typemap::from_canonical(&canonical, target_dialect).sql_type
    };

    let mut parts = vec![format!("    {qname} {type_str}")];

    // NOT NULL (skip for auto-increment PKs where NOT NULL is implied)
    if !col.is_nullable && !(is_auto && is_pk) {
        parts.push("NOT NULL".to_string());
    }

    // DEFAULT (skip for auto-increment columns).
    // MySQL <8.0.13 rejects DEFAULT on BLOB/TEXT/GEOMETRY/JSON columns with
    // ERROR 1101; >=8.0.13 only accepts expression defaults wrapped in
    // parens, which would still drop a literal default like '{}'. Conservative
    // behavior here: drop the default when targeting MySQL on a column whose
    // canonical type is in that no-default class. The column still gets
    // created, just without the default. See #34.
    let mysql_target = target_dialect == Dialect::Mysql;
    // CanonicalType::Array also lands here — pg `text[]` serializes to MySQL
    // `JSON` (see mysql::from_canonical), so it inherits the same "no
    // DEFAULT on JSON" rule. Without this, pg→mysql arrays with `'{}'`
    // defaults trip ERROR 1101 the same way native JSON columns do.
    let no_default_on_mysql = mysql_target
        && matches!(
            canonical,
            crate::ddl_typemap::CanonicalType::Json
                | crate::ddl_typemap::CanonicalType::Jsonb
                | crate::ddl_typemap::CanonicalType::Text
                | crate::ddl_typemap::CanonicalType::Bytes { length: None }
                | crate::ddl_typemap::CanonicalType::Array { .. }
        );
    if !is_auto && !no_default_on_mysql {
        if let Some(ref default) = col.column_default {
            let mut ddl_default =
                format_ddl_default_typed(default, source_dialect, target_dialect, is_boolean);
            // Sub-second precision symmetry on MySQL: when the column is
            // `DATETIME(N)` / `TIMESTAMP(N)`, MySQL requires the matching
            // function-default to also carry `(N)` — `DATETIME(6) DEFAULT
            // CURRENT_TIMESTAMP` (no precision) is rejected with
            // ERROR 1067 "Invalid default value". translate_default_function
            // strips precision from the now-family for cross-dialect work
            // (#32); we re-attach it here when targeting mysql so the
            // column type and default precision match. See #36.
            if mysql_target {
                if let Some(p) = temporal_precision(&canonical) {
                    ddl_default = reattach_now_family_precision(&ddl_default, p);
                }
            }
            parts.push(format!("DEFAULT {ddl_default}"));
        }
    }

    // Auto-increment suffix (MySQL, MSSQL, SQLite)
    if is_auto {
        let suffix = format_autoincrement_suffix(col, target_dialect, is_pk);
        if !suffix.is_empty() {
            parts.push(suffix);
        }
    }

    // MySQL inline column comment
    if target_dialect == Dialect::Mysql {
        if let Some(ref comment) = col.comment {
            parts.push(format!("COMMENT '{}'", comment.replace('\'', "''")));
        }
    }

    parts.join(" ")
}

/// Get the type string for an auto-increment column, potentially overriding the base type.
fn format_autoincrement_type(
    col: &ColumnInfo,
    source_dialect: Dialect,
    target_dialect: Dialect,
    is_pk: bool,
) -> String {
    let base_type = ddl_typemap::map_ddl_type(col, source_dialect, target_dialect).sql_type;

    match target_dialect {
        Dialect::Postgres => {
            // Use SERIAL/BIGSERIAL which implies the type
            if base_type.contains("BIG") {
                "BIGSERIAL".to_string()
            } else {
                "SERIAL".to_string()
            }
        }
        Dialect::Sqlite if is_pk => {
            // SQLite AUTOINCREMENT only works with INTEGER PRIMARY KEY
            "INTEGER".to_string()
        }
        _ => base_type,
    }
}

/// Get the auto-increment suffix to append after the type.
fn format_autoincrement_suffix(col: &ColumnInfo, target_dialect: Dialect, is_pk: bool) -> String {
    match target_dialect {
        Dialect::Postgres => String::new(), // SERIAL/BIGSERIAL handles it
        Dialect::Mysql => "AUTO_INCREMENT".to_string(),
        Dialect::Sqlite if is_pk => "PRIMARY KEY AUTOINCREMENT".to_string(),
        Dialect::Sqlite => String::new(),
        Dialect::Mssql => {
            let (start, inc) = col
                .identity
                .as_ref()
                .map(|id| (id.start, id.increment))
                .unwrap_or((1, 1));
            format!("IDENTITY({start}, {inc})")
        }
    }
}

/// Format a default value expression for the target dialect.
/// When `is_boolean` is true, translates 0/1 ↔ true/false across dialects.
pub(super) fn format_ddl_default_typed(
    default: &str,
    source_dialect: Dialect,
    target_dialect: Dialect,
    is_boolean: bool,
) -> String {
    // Step 1: Strip source-specific syntax
    let cleaned = match source_dialect {
        Dialect::Postgres => super::strip_pg_typecast(default),
        Dialect::Mssql => super::strip_mssql_parens(default),
        Dialect::Mysql | Dialect::Sqlite => default.trim(),
    };

    // Step 2: Boolean literal translation (only when column is boolean)
    if is_boolean {
        let lower = cleaned.trim().to_lowercase();
        if (lower == "1" || lower == "true")
            && (target_dialect == Dialect::Postgres || target_dialect == Dialect::Sqlite)
        {
            return "true".to_string();
        }
        if (lower == "0" || lower == "false")
            && (target_dialect == Dialect::Postgres || target_dialect == Dialect::Sqlite)
        {
            return "false".to_string();
        }
        if (lower == "true" || lower == "1")
            && (target_dialect == Dialect::Mysql || target_dialect == Dialect::Mssql)
        {
            return "1".to_string();
        }
        if (lower == "false" || lower == "0")
            && (target_dialect == Dialect::Mysql || target_dialect == Dialect::Mssql)
        {
            return "0".to_string();
        }
    }

    // Step 3: Translate common function names
    let result = translate_default_function(cleaned, target_dialect);

    // Step 4: Quote bare string defaults that MySQL stores without quotes.
    // Numeric values, SQL keywords, function calls, and already-quoted strings pass through.
    ensure_default_quoting(&result)
}

/// Ensure a default value is properly quoted if it's a bare string literal.
/// MySQL stores string defaults without quotes (e.g. `member` instead of `'member'`).
/// Numbers, NULL, function calls (containing parens), boolean keywords,
/// and already-quoted strings are left as-is.
fn ensure_default_quoting(expr: &str) -> String {
    let trimmed = expr.trim();

    // Already quoted
    if (trimmed.starts_with('\'') && trimmed.ends_with('\''))
        || (trimmed.starts_with('"') && trimmed.ends_with('"'))
    {
        return trimmed.to_string();
    }

    // NULL
    if trimmed.eq_ignore_ascii_case("null") {
        return trimmed.to_string();
    }

    // Boolean keywords
    if trimmed.eq_ignore_ascii_case("true") || trimmed.eq_ignore_ascii_case("false") {
        return trimmed.to_string();
    }

    // Numeric (integer or decimal)
    if trimmed.parse::<f64>().is_ok() {
        return trimmed.to_string();
    }

    // Function call (contains parentheses)
    if trimmed.contains('(') {
        return trimmed.to_string();
    }

    // SQL keywords that are valid unquoted defaults
    let upper = trimmed.to_uppercase();
    if matches!(
        upper.as_str(),
        "CURRENT_TIMESTAMP" | "CURRENT_DATE" | "CURRENT_TIME" | "CURRENT_USER"
    ) {
        return trimmed.to_string();
    }

    // Bare string — needs quoting
    format!("'{}'", trimmed.replace('\'', "''"))
}

/// Translate common SQL functions between dialects.
fn translate_default_function(expr: &str, target: Dialect) -> String {
    let lower = expr.trim().to_lowercase();

    // Strip a trailing precision suffix like CURRENT_TIMESTAMP(6). The (6)
    // is meaningful on the source (sub-second precision matches the column's
    // precision), but for cross-dialect translation we collapse to the base
    // function name and let the column-type emission carry precision via
    // CanonicalType::Timestamp.precision (#36). Without this strip, the
    // translation match below misses anything with a precision suffix.
    let base = strip_precision_suffix(&lower);

    // Normalize common "now-style" functions returning a full date+time.
    // Includes MSSQL variants that #32 was missing: GETUTCDATE, SYSDATETIME,
    // SYSDATETIMEOFFSET, plus PG/SQL standard LOCALTIMESTAMP. None of these
    // are TZ-class load-bearing here — the column's TZ is preserved by the
    // type-mapping path; this function just picks a target-dialect-idiomatic
    // "now" function so the apply step doesn't fail with "function does not
    // exist" on PG/MySQL.
    let is_now_dt = matches!(
        base.as_str(),
        "now()"
            | "now"
            | "current_timestamp"
            | "current_timestamp()"
            | "localtimestamp"
            | "localtimestamp()"
            | "getdate()"
            | "getutcdate()"
            | "sysdatetime()"
            | "sysdatetimeoffset()"
    );
    if is_now_dt {
        return match target {
            Dialect::Postgres => "now()".to_string(),
            Dialect::Mysql | Dialect::Sqlite => "CURRENT_TIMESTAMP".to_string(),
            Dialect::Mssql => "GETDATE()".to_string(),
        };
    }

    // UUID generators
    if base == "gen_random_uuid()" || base == "uuid()" || base == "newid()" {
        return match target {
            Dialect::Postgres => "gen_random_uuid()".to_string(),
            Dialect::Mysql => "(UUID())".to_string(),
            Dialect::Mssql => "NEWID()".to_string(),
            Dialect::Sqlite => "NULL".to_string(), // No native UUID in SQLite
        };
    }

    // Pass through as-is (string literals, numbers, etc.)
    // Note: boolean 0/1 ↔ true/false translation is handled in format_ddl_default_typed()
    // with is_boolean flag to avoid converting integer defaults.
    expr.to_string()
}

/// Conservative cross-dialect portability check for a CHECK predicate.
/// Returns false when the predicate contains tokens we know don't translate
/// without AST-level rewriting — emit-then-fail would abort the table apply
/// (#33 scope note: predicate semantic translation is a separate effort).
///
/// Currently flags:
///   - PG `~` / `~*` regex operators (no MSSQL/MySQL equivalent)
///   - PG `ARRAY[...]` literals (no non-PG dialect has array literal syntax)
///   - PG `ANY(ARRAY[...])` / `ALL(ARRAY[...])` quantified expressions
///
/// All flags fire for any non-PG target — none of MSSQL/MySQL/SQLite have
/// equivalents for these PG-specific constructs. (Earlier doc said "when
/// target=MSSQL" for the array case; the implementation has always been
/// broader than that.)
///
/// Heuristic by token search; misclassifies if a string literal happens to
/// contain `~` or `ARRAY[`, but that's rare in CHECK predicates.
fn check_predicate_is_portable(expr: &str, source: Dialect, target: Dialect) -> bool {
    if source == target {
        return true;
    }
    if source == Dialect::Postgres {
        // PG regex operators don't exist on MSSQL/MySQL.
        if expr.contains('~') {
            return false;
        }
        // PG array literals — `ARRAY[1,2,3]` in CHECK is not portable.
        let lower = expr.to_lowercase();
        if lower.contains("array[") || lower.contains(" any(") || lower.contains(" all(") {
            return false;
        }
    }
    // MySQL CHECKs are usually portable (basic comparisons, IN, IS NULL),
    // but MySQL-specific function names like `IF()` are out of scope. We
    // don't currently flag those — falls back to apply-time error if hit.
    true
}

/// Translate dialect-specific syntax in a CHECK predicate when crossing
/// dialects. Each source dialect has quirks the target dialect's parser
/// rejects:
///   - MySQL: backtick-quoted identifiers `\`col\`` (target=non-mysql)
///   - MSSQL: bracket-quoted identifiers `[col]` (target=non-mssql)
///   - PostgreSQL: `::type` cast suffixes (target=non-pg)
///
/// Same-dialect emission passes through verbatim. Other quirks (regex
/// operators, function-call differences) are out of scope — the predicate
/// would need AST-level translation to handle those, which is a separate
/// effort. See #35.
fn translate_check_predicate(expr: &str, source: Dialect, target: Dialect) -> String {
    if source == target {
        return expr.to_string();
    }
    match source {
        Dialect::Mysql => expr.replace('`', "\""),
        Dialect::Mssql => translate_mssql_check_predicate(expr),
        Dialect::Postgres => strip_pg_casts_in_predicate(expr),
        Dialect::Sqlite => expr.to_string(),
    }
}

/// Replace `[ident]` with `"ident"` in a MSSQL predicate. Doesn't try to
/// parse — just swaps the bracket characters for double-quotes. Edge case:
/// brackets inside a string literal would be miscounted, but real CHECK
/// predicates don't typically embed `[` in strings.
fn translate_mssql_check_predicate(expr: &str) -> String {
    expr.replace('[', "\"").replace(']', "\"")
}

/// Strip PG `::type` and `::type(N)` cast suffixes from a predicate. PG's
/// pg_get_constraintdef emits explicit casts like `(code)::text = upper(...)`
/// or `id::int4 > 0`. Other dialects' parsers reject `::`. We scan for
/// `::`, then consume an identifier and an optional parenthesized arg
/// list. Everything else passes through unchanged.
///
/// Implementation note: copy non-cast spans as UTF-8 string slices via
/// `push_str(&expr[last..i])` rather than byte-by-byte. The cast tokens
/// themselves are pure ASCII (`::`, identifier, parens, digits) so byte-
/// level scanning of the cast region is safe; only the surrounding text
/// might contain non-ASCII (accented string literals in CHECK predicates),
/// which the slice-copy approach preserves intact.
fn strip_pg_casts_in_predicate(expr: &str) -> String {
    let bytes = expr.as_bytes();
    let mut out = String::with_capacity(expr.len());
    let mut i = 0;
    let mut last_copied = 0;
    while i < bytes.len() {
        if i + 1 < bytes.len() && bytes[i] == b':' && bytes[i + 1] == b':' {
            // Flush the run of bytes since the previous skip — slice copy
            // preserves any non-ASCII content (accented string literals,
            // etc.) intact.
            out.push_str(&expr[last_copied..i]);
            // Skip "::"
            i += 2;
            // Skip the type identifier — alphanumeric and underscore only.
            // Don't consume spaces; trailing space is part of the surrounding
            // expression (e.g. `(code)::text = ...` — the space before `=`
            // must survive). PG's multi-word type names (`timestamp without
            // time zone`) aren't typically used in CHECK predicates with
            // explicit casts, so this short-form match is sufficient.
            while i < bytes.len() && (bytes[i].is_ascii_alphanumeric() || bytes[i] == b'_') {
                i += 1;
            }
            // Skip optional parenthesized arg list, e.g. ::numeric(10,2)
            if i < bytes.len() && bytes[i] == b'(' {
                let mut depth = 1;
                i += 1;
                while i < bytes.len() && depth > 0 {
                    match bytes[i] {
                        b'(' => depth += 1,
                        b')' => depth -= 1,
                        _ => {}
                    }
                    i += 1;
                }
            }
            last_copied = i;
        } else {
            i += 1;
        }
    }
    // Tail flush — copy whatever's after the last cast (or the entire
    // input if no cast was found).
    out.push_str(&expr[last_copied..]);
    out
}

/// Extract the sub-second precision from a CanonicalType::Time / Timestamp,
/// or None for non-temporal types or temporals without a stored precision.
/// Used for MySQL DATETIME(N)/TIMESTAMP(N) default-precision symmetry (#36).
fn temporal_precision(ct: &crate::ddl_typemap::CanonicalType) -> Option<u8> {
    match ct {
        crate::ddl_typemap::CanonicalType::Time { precision, .. }
        | crate::ddl_typemap::CanonicalType::Timestamp { precision, .. } => *precision,
        _ => None,
    }
}

/// Re-attach a precision suffix `(N)` to a now-family default expression
/// (CURRENT_TIMESTAMP / GETDATE() / now() / etc.) when targeting MySQL.
/// Idempotent: if `default` already has a parenthesized arg list, leave it
/// alone. The translate_default_function path strips precision for
/// cross-dialect translation; this re-attachment runs after that strip,
/// re-establishing column-type ↔ default-precision symmetry.
fn reattach_now_family_precision(default: &str, precision: u8) -> String {
    let trimmed = default.trim_end();
    // Already has a non-empty paren-arg list (e.g. CURRENT_TIMESTAMP(6),
    // SYSDATETIMEOFFSET(3)) — leave verbatim. Empty parens like `now()`
    // are handled below by replacing them with the precision suffix.
    if trimmed.ends_with(')') && !trimmed.ends_with("()") {
        return default.to_string();
    }
    // Recognize the now-family keywords that ACCEPT a fractional-seconds
    // precision argument (per MySQL grammar). CURRENT_DATE explicitly does
    // NOT — `CURRENT_DATE(6)` is a parser error in MySQL — so it's omitted
    // here. The set is: CURRENT_TIMESTAMP, CURRENT_TIME, LOCALTIME,
    // LOCALTIMESTAMP, NOW (and the function variants handled below).
    let lower = trimmed.to_lowercase();
    let is_now_keyword = matches!(
        lower.as_str(),
        "current_timestamp" | "current_time" | "localtimestamp" | "localtime"
    );
    let is_now_func_no_args = lower.ends_with("()")
        && (lower.starts_with("now")
            || lower.starts_with("getdate")
            || lower.starts_with("getutcdate")
            || lower.starts_with("sysdatetime")
            || lower.starts_with("current_timestamp"));
    if is_now_keyword {
        return format!("{trimmed}({precision})");
    }
    if is_now_func_no_args {
        // Replace the trailing "()" with "(N)".
        let stripped = &trimmed[..trimmed.len() - 2];
        return format!("{stripped}({precision})");
    }
    default.to_string()
}

/// Strip a trailing `(N)` precision suffix from a function-call expression.
/// `current_timestamp(6)` → `current_timestamp()`; `now()` → `now()`;
/// `getdate()` → `getdate()`. Caller passes a lowercased string. Used by
/// the now-family translation so a precision-bearing source default can
/// still match the dialect-idiomatic mapping table.
fn strip_precision_suffix(lower: &str) -> String {
    if let Some(open) = lower.rfind('(') {
        let close = lower.len();
        if close >= open + 2 && lower.ends_with(')') {
            // Inside the parens — if it's all digits (or empty), strip them.
            let inside = &lower[open + 1..close - 1];
            if inside.is_empty() || inside.chars().all(|c| c.is_ascii_digit()) {
                let mut out = lower[..open].to_string();
                out.push_str("()");
                return out;
            }
        }
    }
    lower.to_string()
}

/// Generate a qualified table name with schema prefix if non-default.
/// Maps source default schemas to target default schemas (e.g. PG "public" → MSSQL "dbo").
pub(super) fn qualified_table_name(schema: &str, table: &str, dialect: Dialect) -> String {
    let default_schema = dialect.default_schema();

    // Suppress schema if it matches the target's default
    if schema.is_empty() || schema == default_schema {
        return quote_identifier(table, dialect);
    }

    // Map other dialects' default schemas to the target's default.
    // This covers PG "public" → MSSQL (use dbo), MSSQL "dbo" → PG (use public),
    // and SQLite "main".
    let is_source_default_schema = schema == "public" || schema == "dbo" || schema == "main";

    // For MySQL targets, the schema IS the database name — always suppress it
    // since the target connection already specifies the database.
    let suppress_for_mysql_target = dialect == Dialect::Mysql;

    if is_source_default_schema || suppress_for_mysql_target {
        return quote_identifier(table, dialect);
    }

    format!(
        "{}.{}",
        quote_identifier(schema, dialect),
        quote_identifier(table, dialect)
    )
}

/// Generate CREATE INDEX statements for a table.
pub(super) fn generate_indexes(table: &TableInfo, target_dialect: Dialect) -> Vec<String> {
    let mut stmts = Vec::new();
    let tname = qualified_table_name(&table.schema, &table.name, target_dialect);

    for idx in &table.indexes {
        if is_unique_constraint_index(idx, &table.constraints) {
            continue;
        }

        let unique = if idx.is_unique { "UNIQUE " } else { "" };
        let cols: Vec<String> = idx
            .columns
            .iter()
            .map(|c| quote_identifier(c, target_dialect))
            .collect();
        stmts.push(format!(
            "CREATE {unique}INDEX {} ON {tname} ({});",
            quote_identifier(&idx.name, target_dialect),
            cols.join(", ")
        ));
    }

    stmts
}

/// Generate COMMENT ON statements (PG only; MySQL is inline).
fn generate_comments(table: &TableInfo, target_dialect: Dialect) -> Vec<String> {
    // Only PG uses separate COMMENT ON statements
    if target_dialect != Dialect::Postgres {
        return vec![];
    }

    let mut stmts = Vec::new();
    let tname = qualified_table_name(&table.schema, &table.name, target_dialect);

    if let Some(ref comment) = table.comment {
        stmts.push(format!(
            "COMMENT ON TABLE {tname} IS '{}';",
            comment.replace('\'', "''")
        ));
    }

    for col in &table.columns {
        if let Some(ref comment) = col.comment {
            stmts.push(format!(
                "COMMENT ON COLUMN {tname}.{} IS '{}';",
                quote_identifier(&col.name, target_dialect),
                comment.replace('\'', "''")
            ));
        }
    }

    stmts
}

/// Generate CREATE TYPE statements for enums (PG target only).
fn generate_enum_types(schema: &IntrospectedSchema, target_dialect: Dialect) -> Vec<String> {
    if target_dialect != Dialect::Postgres || schema.enums.is_empty() {
        return vec![];
    }

    schema
        .enums
        .iter()
        .map(|e| {
            let qname = quote_identifier(&e.name, target_dialect);
            let values: Vec<String> = e
                .values
                .iter()
                .map(|v| format!("'{}'", v.replace('\'', "''")))
                .collect();
            format!("CREATE TYPE {qname} AS ENUM ({});", values.join(", "))
        })
        .collect()
}

/// Detect circular FK dependencies among tables.
fn detect_fk_cycles(tables: &[TableInfo]) -> bool {
    use std::collections::HashSet;

    type Key<'a> = (&'a str, &'a str);

    let table_keys: HashSet<Key> = tables
        .iter()
        .map(|t| (t.schema.as_str(), t.name.as_str()))
        .collect();
    let mut visited: HashSet<Key> = HashSet::new();
    let mut in_stack: HashSet<Key> = HashSet::new();

    fn dfs<'a>(
        node: Key<'a>,
        adj: &HashMap<Key<'a>, Vec<Key<'a>>>,
        visited: &mut HashSet<Key<'a>>,
        in_stack: &mut HashSet<Key<'a>>,
    ) -> bool {
        visited.insert(node);
        in_stack.insert(node);
        if let Some(neighbors) = adj.get(&node) {
            for &neighbor in neighbors {
                if !visited.contains(&neighbor) {
                    if dfs(neighbor, adj, visited, in_stack) {
                        return true;
                    }
                } else if in_stack.contains(&neighbor) {
                    return true;
                }
            }
        }
        in_stack.remove(&node);
        false
    }

    let mut adj: HashMap<Key, Vec<Key>> = HashMap::new();
    for table in tables {
        let src = (table.schema.as_str(), table.name.as_str());
        for c in &table.constraints {
            if c.constraint_type == ConstraintType::ForeignKey {
                if let Some(ref fk) = c.foreign_key {
                    let dst = (fk.ref_schema.as_str(), fk.ref_table.as_str());
                    if table_keys.contains(&dst) && dst != src {
                        adj.entry(src).or_default().push(dst);
                    }
                }
            }
        }
    }

    for table in tables {
        let key = (table.schema.as_str(), table.name.as_str());
        if !visited.contains(&key) {
            if dfs(key, &adj, &mut visited, &mut in_stack) {
                return true;
            }
        }
    }
    false
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::testutil::{col, schema_pg, table};

    #[test]
    fn test_quote_identifier_pg() {
        assert_eq!(quote_identifier("users", Dialect::Postgres), "\"users\"");
        assert_eq!(
            quote_identifier("my\"table", Dialect::Postgres),
            "\"my\"\"table\""
        );
    }

    #[test]
    fn test_quote_identifier_mysql() {
        assert_eq!(quote_identifier("users", Dialect::Mysql), "`users`");
    }

    #[test]
    fn test_quote_identifier_mssql() {
        assert_eq!(quote_identifier("users", Dialect::Mssql), "[users]");
    }

    #[test]
    fn test_translate_default_now() {
        assert_eq!(
            translate_default_function("now()", Dialect::Mysql),
            "CURRENT_TIMESTAMP"
        );
        assert_eq!(
            translate_default_function("GETDATE()", Dialect::Postgres),
            "now()"
        );
        assert_eq!(
            translate_default_function("CURRENT_TIMESTAMP", Dialect::Mssql),
            "GETDATE()"
        );
    }

    #[test]
    fn test_translate_default_now_extended() {
        // #32 — MSSQL now-family variants previously not in the keyword list.
        // Each MUST translate to a target-dialect-idiomatic "now" function;
        // leaving them verbatim caused the apply step to fail with
        // "function getutcdate() does not exist" on PG.
        assert_eq!(
            translate_default_function("getutcdate()", Dialect::Postgres),
            "now()"
        );
        assert_eq!(
            translate_default_function("getutcdate()", Dialect::Mysql),
            "CURRENT_TIMESTAMP"
        );
        assert_eq!(
            translate_default_function("sysdatetime()", Dialect::Postgres),
            "now()"
        );
        assert_eq!(
            translate_default_function("LOCALTIMESTAMP", Dialect::Mysql),
            "CURRENT_TIMESTAMP"
        );

        // Precision-suffix stripping: CURRENT_TIMESTAMP(6) and now()-with-precision
        // should still be recognized as the now-family. (#36 caveat: the column
        // type carries the precision via CanonicalType::Timestamp; the default
        // expression becomes plain CURRENT_TIMESTAMP / GETDATE() / now().)
        assert_eq!(
            translate_default_function("CURRENT_TIMESTAMP(6)", Dialect::Mysql),
            "CURRENT_TIMESTAMP"
        );
        assert_eq!(
            translate_default_function("now(3)", Dialect::Mssql),
            "GETDATE()"
        );
    }

    #[test]
    fn test_translate_check_predicate_mssql_brackets() {
        // MSSQL→non-MSSQL: square-bracket identifiers must become
        // double-quotes (which PG and MySQL accept).
        let mssql = "([code]=upper([code]))";
        assert_eq!(
            translate_check_predicate(mssql, Dialect::Mssql, Dialect::Postgres),
            "(\"code\"=upper(\"code\"))"
        );
        // MSSQL→MSSQL: brackets pass through.
        assert_eq!(
            translate_check_predicate(mssql, Dialect::Mssql, Dialect::Mssql),
            mssql
        );
    }

    #[test]
    fn test_check_predicate_is_portable() {
        // Portable: simple comparison + UPPER/IS NULL/IN — works across all dialects.
        assert!(check_predicate_is_portable(
            "(salary >= 0)",
            Dialect::Postgres,
            Dialect::Mssql
        ));
        assert!(check_predicate_is_portable(
            "(code = upper(code))",
            Dialect::Postgres,
            Dialect::Mssql
        ));
        assert!(check_predicate_is_portable(
            "(active in (0,1))",
            Dialect::Postgres,
            Dialect::Mysql
        ));
        assert!(check_predicate_is_portable(
            "(end_at >= start_at OR end_at IS NULL)",
            Dialect::Postgres,
            Dialect::Mssql
        ));

        // Non-portable: PG regex operators have no MSSQL/MySQL equivalent.
        assert!(!check_predicate_is_portable(
            r"(email ~ '^[^@]+@[^@]+\.[^@]+$')",
            Dialect::Postgres,
            Dialect::Mssql
        ));
        // Non-portable: PG ARRAY[...] literals.
        assert!(!check_predicate_is_portable(
            "(customer_type = ANY(ARRAY['individual'::text, 'company'::text]))",
            Dialect::Postgres,
            Dialect::Mssql
        ));

        // Same-dialect always portable, regardless of content.
        assert!(check_predicate_is_portable(
            r"(email ~ '^[^@]+@[^@]+\.[^@]+$')",
            Dialect::Postgres,
            Dialect::Postgres
        ));
    }

    #[test]
    fn test_strip_pg_casts_in_predicate() {
        // PG→non-PG: `::type` casts must be stripped — other dialects'
        // parsers reject the `::` syntax outright.
        assert_eq!(
            strip_pg_casts_in_predicate("(code)::text = upper((code)::text)"),
            "(code) = upper((code))"
        );
        assert_eq!(
            strip_pg_casts_in_predicate("price::numeric(10, 2) > 0"),
            "price > 0"
        );
        // No-op on inputs without casts.
        assert_eq!(strip_pg_casts_in_predicate("salary >= 0"), "salary >= 0");
        // Same-dialect (PG→PG) leaves casts intact via translate_check_predicate.
        assert_eq!(
            translate_check_predicate(
                "(code)::text = upper((code)::text)",
                Dialect::Postgres,
                Dialect::Postgres
            ),
            "(code)::text = upper((code)::text)"
        );
    }

    #[test]
    fn test_translate_check_predicate_backticks() {
        // #35 — MySQL information_schema returns CHECK predicates with
        // backtick-quoted identifiers. Other dialects don't accept backticks;
        // translate to double-quotes when source=mysql and target!=mysql.
        let mysql_predicate = "(`is_active` in (0,1))";

        // mysql → pg: backticks become double-quotes
        assert_eq!(
            translate_check_predicate(mysql_predicate, Dialect::Mysql, Dialect::Postgres),
            "(\"is_active\" in (0,1))"
        );
        // mysql → mssql: same translation (MSSQL accepts double-quotes with QUOTED_IDENTIFIER on)
        assert_eq!(
            translate_check_predicate(mysql_predicate, Dialect::Mysql, Dialect::Mssql),
            "(\"is_active\" in (0,1))"
        );
        // mysql → mysql: pass through
        assert_eq!(
            translate_check_predicate(mysql_predicate, Dialect::Mysql, Dialect::Mysql),
            mysql_predicate
        );
        // pg → mssql: no transformation needed (no backticks in pg predicates)
        assert_eq!(
            translate_check_predicate("(salary >= 0)", Dialect::Postgres, Dialect::Mssql),
            "(salary >= 0)"
        );
    }

    #[test]
    fn test_reattach_now_family_precision() {
        // #36 — MySQL DATETIME(N) requires DEFAULT CURRENT_TIMESTAMP(N).
        // After translate_default_function strips precision, this re-attach
        // step puts it back when emitting against a mysql target with a
        // precision-bearing column type.
        assert_eq!(
            reattach_now_family_precision("CURRENT_TIMESTAMP", 6),
            "CURRENT_TIMESTAMP(6)"
        );
        assert_eq!(reattach_now_family_precision("now()", 3), "now(3)");
        assert_eq!(reattach_now_family_precision("GETDATE()", 6), "GETDATE(6)");
        // Idempotent: already-precise expression unchanged.
        assert_eq!(
            reattach_now_family_precision("CURRENT_TIMESTAMP(6)", 6),
            "CURRENT_TIMESTAMP(6)"
        );
        // Non-now-family: passes through (no inappropriate precision append).
        assert_eq!(reattach_now_family_precision("'pending'", 6), "'pending'");
        assert_eq!(reattach_now_family_precision("42", 6), "42");
        // CURRENT_DATE does NOT accept FSP in MySQL — it's a date-only
        // function, no fractional-seconds component. We must NOT append
        // precision, even though it's a "now"-family keyword textually.
        // Per Copilot review on PR #37.
        assert_eq!(
            reattach_now_family_precision("CURRENT_DATE", 6),
            "CURRENT_DATE"
        );
    }

    #[test]
    fn test_strip_precision_suffix() {
        assert_eq!(strip_precision_suffix("now()"), "now()");
        assert_eq!(
            strip_precision_suffix("current_timestamp(6)"),
            "current_timestamp()"
        );
        assert_eq!(strip_precision_suffix("getdate(3)"), "getdate()");
        // Non-digit content stays as-is (defensive: don't strip user functions).
        assert_eq!(strip_precision_suffix("foo(bar)"), "foo(bar)");
    }

    #[test]
    fn test_translate_default_uuid() {
        assert_eq!(
            translate_default_function("gen_random_uuid()", Dialect::Mysql),
            "(UUID())"
        );
        assert_eq!(
            translate_default_function("NEWID()", Dialect::Postgres),
            "gen_random_uuid()"
        );
    }

    #[test]
    fn test_json_default_dropped_on_mysql_target() {
        // #34 — MySQL <8.0.13 rejects DEFAULT on JSON/TEXT/BLOB. uvg should
        // drop the default when targeting MySQL on these types rather than
        // emit a literal that fails at apply time with ERROR 1101.
        let mut json_col = col("settings").udt("jsonb").build();
        json_col.column_default = Some("'{}'::jsonb".to_string());
        let mut text_col = col("notes").udt("text").build();
        text_col.column_default = Some("'pending'::text".to_string());
        let mut blob_col = col("payload").udt("bytea").build();
        blob_col.column_default = Some("'\\x00'::bytea".to_string());
        let t = table("docs")
            .schema("")
            .column(col("id").build())
            .column(json_col)
            .column(text_col)
            .column(blob_col)
            .pk("pk_docs", &["id"])
            .build();

        let options = DdlOptions {
            target_dialect: Dialect::Mysql,
            split_tables: false,
            apply: false,
            noindexes: false,
            noconstraints: false,
            nocomments: false,
        };
        let ddl = generate_create_table(&t, Dialect::Postgres, Dialect::Mysql, &options);

        // The columns themselves are still emitted; only the DEFAULT is dropped.
        assert!(ddl.contains("`settings` JSON"), "DDL was: {ddl}");
        assert!(ddl.contains("`notes` TEXT"), "DDL was: {ddl}");
        assert!(ddl.contains("`payload` BLOB"), "DDL was: {ddl}");
        // No DEFAULT clause should appear for any of these columns.
        assert!(
            !ddl.contains("`settings` JSON NOT NULL DEFAULT"),
            "default leaked: {ddl}"
        );
        assert!(
            !ddl.contains("`notes` TEXT NOT NULL DEFAULT"),
            "default leaked: {ddl}"
        );
        assert!(
            !ddl.contains("`payload` BLOB NOT NULL DEFAULT"),
            "default leaked: {ddl}"
        );
    }

    #[test]
    fn test_json_default_kept_on_pg_target() {
        // Negative case for #34 — only MySQL targets drop the default. PG
        // accepts JSON defaults so the default must pass through normally.
        let mut json_col = col("settings").udt("jsonb").build();
        json_col.column_default = Some("'{}'::jsonb".to_string());
        let t = table("docs")
            .schema("")
            .column(col("id").build())
            .column(json_col)
            .pk("pk_docs", &["id"])
            .build();
        let options = DdlOptions {
            target_dialect: Dialect::Postgres,
            split_tables: false,
            apply: false,
            noindexes: false,
            noconstraints: false,
            nocomments: false,
        };
        let ddl = generate_create_table(&t, Dialect::Postgres, Dialect::Postgres, &options);
        assert!(
            ddl.contains("DEFAULT '{}'"),
            "PG should preserve JSON default: {ddl}"
        );
    }

    #[test]
    fn test_generate_create_table_pg_to_mysql() {
        let t = table("users")
            .schema("")
            .column(col("id").build())
            .column(col("name").udt("varchar").max_length(100).build())
            .column(col("bio").udt("text").nullable().build())
            .pk("pk_users", &["id"])
            .build();
        let options = DdlOptions {
            target_dialect: Dialect::Mysql,
            split_tables: false,
            apply: false,
            noindexes: false,
            noconstraints: false,
            nocomments: false,
        };
        let ddl = generate_create_table(&t, Dialect::Postgres, Dialect::Mysql, &options);
        assert!(ddl.contains("CREATE TABLE `users`"), "DDL was: {ddl}");
        assert!(ddl.contains("`id` INT NOT NULL"), "DDL was: {ddl}");
        assert!(
            ddl.contains("`name` VARCHAR(100) NOT NULL"),
            "DDL was: {ddl}"
        );
        assert!(ddl.contains("`bio` TEXT"), "DDL was: {ddl}");
        assert!(ddl.contains("PRIMARY KEY (`id`)"), "DDL was: {ddl}");
    }

    #[test]
    fn test_generate_create_table_pg_to_pg() {
        let t = table("items")
            .column(col("id").build())
            .column(col("price").udt("numeric").precision(10, 2).build())
            .pk("pk_items", &["id"])
            .build();
        let options = DdlOptions {
            target_dialect: Dialect::Postgres,
            split_tables: false,
            apply: false,
            noindexes: false,
            noconstraints: false,
            nocomments: false,
        };
        let ddl = generate_create_table(&t, Dialect::Postgres, Dialect::Postgres, &options);
        assert!(ddl.contains("\"id\" INTEGER NOT NULL"));
        assert!(ddl.contains("\"price\" NUMERIC(10, 2) NOT NULL"));
    }

    #[test]
    fn test_full_generate_single() {
        let schema = schema_pg(vec![table("users")
            .schema("")
            .column(col("id").build())
            .column(col("name").udt("varchar").max_length(100).build())
            .pk("pk_users", &["id"])
            .build()]);
        let options = DdlOptions {
            target_dialect: Dialect::Mysql,
            split_tables: false,
            apply: false,
            noindexes: false,
            noconstraints: false,
            nocomments: false,
        };
        let gen = DdlGenerator;
        match gen.generate(&schema, None, &options) {
            DdlOutput::Single(ddl) => {
                assert!(ddl.contains("CREATE TABLE `users`"));
                assert!(ddl.contains("Source: postgres, Target: mysql"));
            }
            DdlOutput::Split(_) => panic!("Expected single output"),
        }
    }

    #[test]
    fn test_full_generate_split() {
        let schema = schema_pg(vec![
            table("users")
                .column(col("id").build())
                .pk("pk_users", &["id"])
                .build(),
            table("posts")
                .column(col("id").build())
                .pk("pk_posts", &["id"])
                .build(),
        ]);
        let options = DdlOptions {
            target_dialect: Dialect::Postgres,
            split_tables: true,
            apply: false,
            noindexes: false,
            noconstraints: false,
            nocomments: false,
        };
        match DdlGenerator.generate(&schema, None, &options) {
            DdlOutput::Split(files) => {
                let names: Vec<&str> = files.iter().map(|(n, _)| n.as_str()).collect();
                assert!(names.contains(&"users.sql"));
                assert!(names.contains(&"posts.sql"));
                assert!(names.contains(&"_order.txt"));
            }
            DdlOutput::Single(_) => panic!("Expected split output"),
        }
    }

    #[test]
    fn test_boolean_default_mssql_to_pg() {
        assert_eq!(
            format_ddl_default_typed("((1))", Dialect::Mssql, Dialect::Postgres, true),
            "true"
        );
        assert_eq!(
            format_ddl_default_typed("((0))", Dialect::Mssql, Dialect::Postgres, true),
            "false"
        );
    }

    #[test]
    fn test_integer_default_not_converted_to_boolean() {
        assert_eq!(
            format_ddl_default_typed("((0))", Dialect::Mssql, Dialect::Postgres, false),
            "0"
        );
        assert_eq!(
            format_ddl_default_typed("((1))", Dialect::Mssql, Dialect::Postgres, false),
            "1"
        );
    }

    #[test]
    fn test_boolean_default_pg_to_mysql() {
        assert_eq!(
            format_ddl_default_typed("true", Dialect::Postgres, Dialect::Mysql, true),
            "1"
        );
        assert_eq!(
            format_ddl_default_typed("false", Dialect::Postgres, Dialect::Mysql, true),
            "0"
        );
    }

    #[test]
    fn test_boolean_default_pg_to_mssql() {
        assert_eq!(
            format_ddl_default_typed("true", Dialect::Postgres, Dialect::Mssql, true),
            "1"
        );
        assert_eq!(
            format_ddl_default_typed("false", Dialect::Postgres, Dialect::Mssql, true),
            "0"
        );
    }

    #[test]
    fn test_ensure_default_quoting() {
        assert_eq!(ensure_default_quoting("member"), "'member'");
        assert_eq!(ensure_default_quoting("active"), "'active'");
        assert_eq!(ensure_default_quoting("'member'"), "'member'");
        assert_eq!(ensure_default_quoting("0"), "0");
        assert_eq!(ensure_default_quoting("3.14"), "3.14");
        assert_eq!(ensure_default_quoting("NULL"), "NULL");
        assert_eq!(ensure_default_quoting("true"), "true");
        assert_eq!(ensure_default_quoting("false"), "false");
        assert_eq!(ensure_default_quoting("now()"), "now()");
        assert_eq!(
            ensure_default_quoting("CURRENT_TIMESTAMP"),
            "CURRENT_TIMESTAMP"
        );
        assert_eq!(ensure_default_quoting("it's"), "'it''s'");
    }
}
