mod checks;
mod column;
mod comments;
mod create_table;
mod cycles;
mod defaults;
mod enums;
mod ident;
mod indexes;

use crate::cli::DdlOptions;
use crate::codegen::topo_sort_tables;
#[cfg(test)]
use crate::dialect::Dialect;
use crate::schema::{IntrospectedSchema, TableInfo, TableType};

#[cfg(test)]
use checks::{check_predicate_is_portable, strip_pg_casts_in_predicate, translate_check_predicate};
pub(super) use column::generate_column_def;
use comments::generate_comments;
pub(super) use create_table::generate_create_table;
use cycles::detect_fk_cycles;
pub(super) use defaults::format_ddl_default_typed;
#[cfg(test)]
use defaults::{
    ensure_default_quoting, reattach_now_family_precision, strip_precision_suffix,
    translate_default_function,
};
use enums::generate_enum_types;
pub(super) use ident::{qualified_table_name, quote_identifier};
pub(super) use indexes::generate_indexes;

/// Output from DDL generation.
pub enum DdlOutput {
    Single(String),
    Split(Vec<(String, String)>),
}

pub struct DdlGenerator;

impl DdlGenerator {
    pub fn generate(
        &self,
        schema: &IntrospectedSchema,
        target_schema: Option<&IntrospectedSchema>,
        options: &DdlOptions,
    ) -> DdlOutput {
        match target_schema {
            Some(target) => {
                let ddl = super::ddl_diff::diff_schemas(schema, target, options);
                DdlOutput::Single(ddl)
            }
            None => self.generate_full(schema, options),
        }
    }

    fn generate_full(&self, schema: &IntrospectedSchema, options: &DdlOptions) -> DdlOutput {
        let source_dialect = schema.dialect;
        let target_dialect = options.target_dialect;
        let sorted = topo_sort_tables(&schema.tables);

        // Filter to tables only (skip views for DDL)
        let tables: Vec<&&TableInfo> = sorted
            .iter()
            .filter(|t| t.table_type == TableType::Table)
            .collect();

        let mut all_stmts: Vec<String> = Vec::new();
        let mut per_table: Vec<(String, String)> = Vec::new();

        // Detect circular FK dependencies — warn if cycles exist
        let has_cycles = detect_fk_cycles(&schema.tables);

        // Header
        let mut header =
            format!("-- Generated by uvg\n-- Source: {source_dialect}, Target: {target_dialect}\n");
        if has_cycles {
            header.push_str("-- WARNING: Circular foreign key dependencies detected.\n-- Some FK constraints may reference tables not yet created.\n-- Consider applying FK constraints separately via ALTER TABLE.\n");
        }

        // Enum types (PG target only)
        let enum_stmts = generate_enum_types(schema, target_dialect);

        for table in &tables {
            let mut table_stmts = Vec::new();

            let create = generate_create_table(table, source_dialect, target_dialect, options);
            table_stmts.push(create);

            if !options.noindexes {
                let indexes = generate_indexes(table, source_dialect, target_dialect);
                table_stmts.extend(indexes);
            }

            if !options.nocomments {
                let comments = generate_comments(table, source_dialect, target_dialect);
                table_stmts.extend(comments);
            }

            let table_ddl = table_stmts.join("\n\n");
            all_stmts.push(table_ddl.clone());
            // Disambiguate filenames by schema for multi-schema introspection
            let filename =
                if table.schema.is_empty() || table.schema == target_dialect.default_schema() {
                    format!("{}.sql", table.name)
                } else {
                    format!("{}_{}.sql", table.schema, table.name)
                };
            per_table.push((filename, table_ddl));
        }

        if options.split_tables {
            let mut files: Vec<(String, String)> = Vec::new();

            if !enum_stmts.is_empty() {
                files.push((
                    "_types.sql".to_string(),
                    format!("{header}\n{}", enum_stmts.join("\n\n")),
                ));
            }

            for (filename, content) in per_table {
                files.push((filename, format!("{header}\n{content}\n")));
            }

            // Order file uses the actual filenames from per_table (already schema-qualified)
            let order: Vec<String> = files
                .iter()
                .filter(|(n, _)| n != "_types.sql")
                .map(|(n, _)| n.clone())
                .collect();
            files.push(("_order.txt".to_string(), order.join("\n") + "\n"));

            DdlOutput::Split(files)
        } else {
            let mut full = header;
            if !enum_stmts.is_empty() {
                full.push('\n');
                full.push_str(&enum_stmts.join("\n\n"));
                full.push_str("\n\n");
            }
            full.push('\n');
            full.push_str(&all_stmts.join("\n\n"));
            full.push('\n');
            DdlOutput::Single(full)
        }
    }
}

#[cfg(test)]
#[path = "ddl_tests.rs"]
mod tests;
