use std::collections::HashMap;

use crate::cli::DdlOptions;
use crate::codegen::{
    is_primary_key_column, is_serial_default, is_unique_constraint_index, topo_sort_tables,
};
use crate::ddl_typemap;
use crate::dialect::Dialect;
use crate::schema::{
    ColumnInfo, ConstraintInfo, ConstraintType, IntrospectedSchema, TableInfo, TableType,
};

/// Output from DDL generation.
pub enum DdlOutput {
    Single(String),
    Split(Vec<(String, String)>),
}

pub struct DdlGenerator;

impl DdlGenerator {
    pub fn generate(
        &self,
        schema: &IntrospectedSchema,
        target_schema: Option<&IntrospectedSchema>,
        options: &DdlOptions,
    ) -> DdlOutput {
        match target_schema {
            Some(target) => {
                let ddl = super::ddl_diff::diff_schemas(schema, target, options);
                DdlOutput::Single(ddl)
            }
            None => self.generate_full(schema, options),
        }
    }

    fn generate_full(&self, schema: &IntrospectedSchema, options: &DdlOptions) -> DdlOutput {
        let source_dialect = schema.dialect;
        let target_dialect = options.target_dialect;
        let sorted = topo_sort_tables(&schema.tables);

        // Filter to tables only (skip views for DDL)
        let tables: Vec<&&TableInfo> = sorted
            .iter()
            .filter(|t| t.table_type == TableType::Table)
            .collect();

        let mut all_stmts: Vec<String> = Vec::new();
        let mut per_table: Vec<(String, String)> = Vec::new();

        // Detect circular FK dependencies — warn if cycles exist
        let has_cycles = detect_fk_cycles(&schema.tables);

        // Header
        let mut header = format!(
            "-- Generated by uvg\n-- Source: {source_dialect}, Target: {target_dialect}\n"
        );
        if has_cycles {
            header.push_str("-- WARNING: Circular foreign key dependencies detected.\n-- Some FK constraints may reference tables not yet created.\n-- Consider applying FK constraints separately via ALTER TABLE.\n");
        }

        // Enum types (PG target only)
        let enum_stmts = generate_enum_types(schema, target_dialect);

        for table in &tables {
            let mut table_stmts = Vec::new();

            let create = generate_create_table(table, source_dialect, target_dialect, options);
            table_stmts.push(create);

            if !options.noindexes {
                let indexes = generate_indexes(table, target_dialect);
                table_stmts.extend(indexes);
            }

            if !options.nocomments {
                let comments = generate_comments(table, target_dialect);
                table_stmts.extend(comments);
            }

            let table_ddl = table_stmts.join("\n\n");
            all_stmts.push(table_ddl.clone());
            // Disambiguate filenames by schema for multi-schema introspection
            let filename = if table.schema.is_empty()
                || table.schema == target_dialect.default_schema()
            {
                format!("{}.sql", table.name)
            } else {
                format!("{}_{}.sql", table.schema, table.name)
            };
            per_table.push((filename, table_ddl));
        }

        if options.split_tables {
            let mut files: Vec<(String, String)> = Vec::new();

            if !enum_stmts.is_empty() {
                files.push(("_types.sql".to_string(), format!("{header}\n{}", enum_stmts.join("\n\n"))));
            }

            for (filename, content) in per_table {
                files.push((filename, format!("{header}\n{content}\n")));
            }

            // Order file uses the actual filenames from per_table (already schema-qualified)
            let order: Vec<String> = files
                .iter()
                .filter(|(n, _)| n != "_types.sql")
                .map(|(n, _)| n.clone())
                .collect();
            files.push(("_order.txt".to_string(), order.join("\n") + "\n"));

            DdlOutput::Split(files)
        } else {
            let mut full = header;
            if !enum_stmts.is_empty() {
                full.push('\n');
                full.push_str(&enum_stmts.join("\n\n"));
                full.push_str("\n\n");
            }
            full.push('\n');
            full.push_str(&all_stmts.join("\n\n"));
            full.push('\n');
            DdlOutput::Single(full)
        }
    }
}

/// Quote an identifier for the target dialect.
pub(super) fn quote_identifier(name: &str, dialect: Dialect) -> String {
    match dialect {
        Dialect::Postgres | Dialect::Sqlite => format!("\"{}\"", name.replace('"', "\"\"")),
        Dialect::Mysql => format!("`{}`", name.replace('`', "``")),
        Dialect::Mssql => format!("[{}]", name.replace(']', "]]")),
    }
}

/// Generate a CREATE TABLE statement.
pub(super) fn generate_create_table(
    table: &TableInfo,
    source_dialect: Dialect,
    target_dialect: Dialect,
    options: &DdlOptions,
) -> String {
    let qname = qualified_table_name(&table.schema, &table.name, target_dialect);
    let mut parts: Vec<String> = Vec::new();

    // Detect if any column has inline PK AUTOINCREMENT (SQLite)
    let has_inline_pk = target_dialect == Dialect::Sqlite
        && table.columns.iter().any(|col| {
            let is_auto = col.is_identity
                || col.autoincrement == Some(true)
                || col
                    .column_default
                    .as_deref()
                    .map(|d| is_serial_default(d, source_dialect))
                    .unwrap_or(false);
            is_auto && is_primary_key_column(&col.name, &table.constraints)
        });

    // Columns
    for col in &table.columns {
        parts.push(generate_column_def(
            col,
            &table.constraints,
            source_dialect,
            target_dialect,
        ));
    }

    // Constraints
    if !options.noconstraints {
        // Primary key (suppress if SQLite auto-increment already emitted inline PK)
        if !has_inline_pk {
            for c in &table.constraints {
                if c.constraint_type == ConstraintType::PrimaryKey {
                    let cols: Vec<String> = c
                        .columns
                        .iter()
                        .map(|col| quote_identifier(col, target_dialect))
                        .collect();
                    parts.push(format!(
                        "    CONSTRAINT {} PRIMARY KEY ({})",
                        quote_identifier(&c.name, target_dialect),
                        cols.join(", ")
                    ));
                }
            }
        }

        // Unique constraints
        for c in &table.constraints {
            if c.constraint_type == ConstraintType::Unique {
                let cols: Vec<String> = c
                    .columns
                    .iter()
                    .map(|col| quote_identifier(col, target_dialect))
                    .collect();
                parts.push(format!(
                    "    CONSTRAINT {} UNIQUE ({})",
                    quote_identifier(&c.name, target_dialect),
                    cols.join(", ")
                ));
            }
        }

        // Foreign keys
        for c in &table.constraints {
            if c.constraint_type == ConstraintType::ForeignKey {
                if let Some(ref fk) = c.foreign_key {
                    let cols: Vec<String> = c
                        .columns
                        .iter()
                        .map(|col| quote_identifier(col, target_dialect))
                        .collect();
                    let ref_table =
                        qualified_table_name(&fk.ref_schema, &fk.ref_table, target_dialect);
                    let ref_cols: Vec<String> = fk
                        .ref_columns
                        .iter()
                        .map(|col| quote_identifier(col, target_dialect))
                        .collect();
                    let mut fk_str = format!(
                        "    CONSTRAINT {} FOREIGN KEY ({}) REFERENCES {} ({})",
                        quote_identifier(&c.name, target_dialect),
                        cols.join(", "),
                        ref_table,
                        ref_cols.join(", ")
                    );
                    if fk.delete_rule != "NO ACTION" {
                        fk_str.push_str(&format!(" ON DELETE {}", fk.delete_rule));
                    }
                    if fk.update_rule != "NO ACTION" {
                        fk_str.push_str(&format!(" ON UPDATE {}", fk.update_rule));
                    }
                    parts.push(fk_str);
                }
            }
        }

        // Check constraints
        for c in &table.constraints {
            if c.constraint_type == ConstraintType::Check {
                if let Some(ref expr) = c.check_expression {
                    parts.push(format!(
                        "    CONSTRAINT {} CHECK ({})",
                        quote_identifier(&c.name, target_dialect),
                        expr
                    ));
                }
            }
        }
    }

    let body = parts.join(",\n");

    // MySQL table comment is inline
    let table_comment = if !options.nocomments && target_dialect == Dialect::Mysql {
        table
            .comment
            .as_ref()
            .map(|c| format!(" COMMENT '{}'", c.replace('\'', "''")))
            .unwrap_or_default()
    } else {
        String::new()
    };

    format!("CREATE TABLE {qname} (\n{body}\n){table_comment};")
}

/// Generate a column definition line.
pub(super) fn generate_column_def(
    col: &ColumnInfo,
    constraints: &[ConstraintInfo],
    source_dialect: Dialect,
    target_dialect: Dialect,
) -> String {
    let qname = quote_identifier(&col.name, target_dialect);

    // Detect auto-increment
    let is_auto = col.is_identity
        || col.autoincrement == Some(true)
        || col
            .column_default
            .as_deref()
            .map(|d| is_serial_default(d, source_dialect))
            .unwrap_or(false);

    let is_pk = is_primary_key_column(&col.name, constraints);

    // Compute canonical type once (used for type mapping and boolean default detection)
    let canonical = crate::ddl_typemap::to_canonical(col, source_dialect);
    let is_boolean = matches!(canonical, crate::ddl_typemap::CanonicalType::Boolean);

    // Type
    let type_str = if is_auto {
        format_autoincrement_type(col, source_dialect, target_dialect, is_pk)
    } else {
        ddl_typemap::from_canonical(&canonical, target_dialect).sql_type
    };

    let mut parts = vec![format!("    {qname} {type_str}")];

    // NOT NULL (skip for auto-increment PKs where NOT NULL is implied)
    if !col.is_nullable && !(is_auto && is_pk) {
        parts.push("NOT NULL".to_string());
    }

    // DEFAULT (skip for auto-increment columns)
    if !is_auto {
        if let Some(ref default) = col.column_default {
            let ddl_default =
                format_ddl_default_typed(default, source_dialect, target_dialect, is_boolean);
            parts.push(format!("DEFAULT {ddl_default}"));
        }
    }

    // Auto-increment suffix (MySQL, MSSQL, SQLite)
    if is_auto {
        let suffix = format_autoincrement_suffix(col, target_dialect, is_pk);
        if !suffix.is_empty() {
            parts.push(suffix);
        }
    }

    // MySQL inline column comment
    if target_dialect == Dialect::Mysql {
        if let Some(ref comment) = col.comment {
            parts.push(format!("COMMENT '{}'", comment.replace('\'', "''")));
        }
    }

    parts.join(" ")
}

/// Get the type string for an auto-increment column, potentially overriding the base type.
fn format_autoincrement_type(
    col: &ColumnInfo,
    source_dialect: Dialect,
    target_dialect: Dialect,
    is_pk: bool,
) -> String {
    let base_type = ddl_typemap::map_ddl_type(col, source_dialect, target_dialect).sql_type;

    match target_dialect {
        Dialect::Postgres => {
            // Use SERIAL/BIGSERIAL which implies the type
            if base_type.contains("BIG") {
                "BIGSERIAL".to_string()
            } else {
                "SERIAL".to_string()
            }
        }
        Dialect::Sqlite if is_pk => {
            // SQLite AUTOINCREMENT only works with INTEGER PRIMARY KEY
            "INTEGER".to_string()
        }
        _ => base_type,
    }
}

/// Get the auto-increment suffix to append after the type.
fn format_autoincrement_suffix(
    col: &ColumnInfo,
    target_dialect: Dialect,
    is_pk: bool,
) -> String {
    match target_dialect {
        Dialect::Postgres => String::new(), // SERIAL/BIGSERIAL handles it
        Dialect::Mysql => "AUTO_INCREMENT".to_string(),
        Dialect::Sqlite if is_pk => "PRIMARY KEY AUTOINCREMENT".to_string(),
        Dialect::Sqlite => String::new(),
        Dialect::Mssql => {
            let (start, inc) = col
                .identity
                .as_ref()
                .map(|id| (id.start, id.increment))
                .unwrap_or((1, 1));
            format!("IDENTITY({start}, {inc})")
        }
    }
}

/// Format a default value expression for the target dialect.
/// When `is_boolean` is true, translates 0/1 ↔ true/false across dialects.
pub(super) fn format_ddl_default_typed(
    default: &str,
    source_dialect: Dialect,
    target_dialect: Dialect,
    is_boolean: bool,
) -> String {
    // Step 1: Strip source-specific syntax
    let cleaned = match source_dialect {
        Dialect::Postgres => super::strip_pg_typecast(default),
        Dialect::Mssql => super::strip_mssql_parens(default),
        Dialect::Mysql | Dialect::Sqlite => default.trim(),
    };

    // Step 2: Boolean literal translation (only when column is boolean)
    if is_boolean {
        let lower = cleaned.trim().to_lowercase();
        if (lower == "1" || lower == "true")
            && (target_dialect == Dialect::Postgres || target_dialect == Dialect::Sqlite)
        {
            return "true".to_string();
        }
        if (lower == "0" || lower == "false")
            && (target_dialect == Dialect::Postgres || target_dialect == Dialect::Sqlite)
        {
            return "false".to_string();
        }
        if (lower == "true" || lower == "1")
            && (target_dialect == Dialect::Mysql || target_dialect == Dialect::Mssql)
        {
            return "1".to_string();
        }
        if (lower == "false" || lower == "0")
            && (target_dialect == Dialect::Mysql || target_dialect == Dialect::Mssql)
        {
            return "0".to_string();
        }
    }

    // Step 3: Translate common function names
    let result = translate_default_function(cleaned, target_dialect);

    // Step 4: Quote bare string defaults that MySQL stores without quotes.
    // Numeric values, SQL keywords, function calls, and already-quoted strings pass through.
    ensure_default_quoting(&result)
}

/// Ensure a default value is properly quoted if it's a bare string literal.
/// MySQL stores string defaults without quotes (e.g. `member` instead of `'member'`).
/// Numbers, NULL, function calls (containing parens), boolean keywords,
/// and already-quoted strings are left as-is.
fn ensure_default_quoting(expr: &str) -> String {
    let trimmed = expr.trim();

    // Already quoted
    if (trimmed.starts_with('\'') && trimmed.ends_with('\''))
        || (trimmed.starts_with('"') && trimmed.ends_with('"'))
    {
        return trimmed.to_string();
    }

    // NULL
    if trimmed.eq_ignore_ascii_case("null") {
        return trimmed.to_string();
    }

    // Boolean keywords
    if trimmed.eq_ignore_ascii_case("true") || trimmed.eq_ignore_ascii_case("false") {
        return trimmed.to_string();
    }

    // Numeric (integer or decimal)
    if trimmed.parse::<f64>().is_ok() {
        return trimmed.to_string();
    }

    // Function call (contains parentheses)
    if trimmed.contains('(') {
        return trimmed.to_string();
    }

    // SQL keywords that are valid unquoted defaults
    let upper = trimmed.to_uppercase();
    if matches!(
        upper.as_str(),
        "CURRENT_TIMESTAMP" | "CURRENT_DATE" | "CURRENT_TIME" | "CURRENT_USER"
    ) {
        return trimmed.to_string();
    }

    // Bare string — needs quoting
    format!("'{}'", trimmed.replace('\'', "''"))
}

/// Translate common SQL functions between dialects.
fn translate_default_function(expr: &str, target: Dialect) -> String {
    let lower = expr.trim().to_lowercase();

    // Normalize common timestamp functions
    if lower == "now()"
        || lower == "current_timestamp"
        || lower == "getdate()"
        || lower == "sysdatetimeoffset()"
    {
        return match target {
            Dialect::Postgres => "now()".to_string(),
            Dialect::Mysql | Dialect::Sqlite => "CURRENT_TIMESTAMP".to_string(),
            Dialect::Mssql => "GETDATE()".to_string(),
        };
    }

    // UUID generators
    if lower == "gen_random_uuid()" || lower == "uuid()" || lower == "newid()" {
        return match target {
            Dialect::Postgres => "gen_random_uuid()".to_string(),
            Dialect::Mysql => "(UUID())".to_string(),
            Dialect::Mssql => "NEWID()".to_string(),
            Dialect::Sqlite => "NULL".to_string(), // No native UUID in SQLite
        };
    }

    // Pass through as-is (string literals, numbers, etc.)
    // Note: boolean 0/1 ↔ true/false translation is handled in format_ddl_default_typed()
    // with is_boolean flag to avoid converting integer defaults.
    expr.to_string()
}

/// Generate a qualified table name with schema prefix if non-default.
/// Maps source default schemas to target default schemas (e.g. PG "public" → MSSQL "dbo").
pub(super) fn qualified_table_name(schema: &str, table: &str, dialect: Dialect) -> String {
    let default_schema = dialect.default_schema();

    // Suppress schema if it matches the target's default
    if schema.is_empty() || schema == default_schema {
        return quote_identifier(table, dialect);
    }

    // Map other dialects' default schemas to the target's default.
    // This covers PG "public" → MSSQL (use dbo), MSSQL "dbo" → PG (use public),
    // and SQLite "main".
    let is_source_default_schema =
        schema == "public" || schema == "dbo" || schema == "main";

    // For MySQL targets, the schema IS the database name — always suppress it
    // since the target connection already specifies the database.
    let suppress_for_mysql_target = dialect == Dialect::Mysql;

    if is_source_default_schema || suppress_for_mysql_target {
        return quote_identifier(table, dialect);
    }

    format!(
        "{}.{}",
        quote_identifier(schema, dialect),
        quote_identifier(table, dialect)
    )
}

/// Generate CREATE INDEX statements for a table.
pub(super) fn generate_indexes(table: &TableInfo, target_dialect: Dialect) -> Vec<String> {
    let mut stmts = Vec::new();
    let tname = qualified_table_name(&table.schema, &table.name, target_dialect);

    for idx in &table.indexes {
        if is_unique_constraint_index(idx, &table.constraints) {
            continue;
        }

        let unique = if idx.is_unique { "UNIQUE " } else { "" };
        let cols: Vec<String> = idx
            .columns
            .iter()
            .map(|c| quote_identifier(c, target_dialect))
            .collect();
        stmts.push(format!(
            "CREATE {unique}INDEX {} ON {tname} ({});",
            quote_identifier(&idx.name, target_dialect),
            cols.join(", ")
        ));
    }

    stmts
}

/// Generate COMMENT ON statements (PG only; MySQL is inline).
fn generate_comments(table: &TableInfo, target_dialect: Dialect) -> Vec<String> {
    // Only PG uses separate COMMENT ON statements
    if target_dialect != Dialect::Postgres {
        return vec![];
    }

    let mut stmts = Vec::new();
    let tname = qualified_table_name(&table.schema, &table.name, target_dialect);

    if let Some(ref comment) = table.comment {
        stmts.push(format!(
            "COMMENT ON TABLE {tname} IS '{}';",
            comment.replace('\'', "''")
        ));
    }

    for col in &table.columns {
        if let Some(ref comment) = col.comment {
            stmts.push(format!(
                "COMMENT ON COLUMN {tname}.{} IS '{}';",
                quote_identifier(&col.name, target_dialect),
                comment.replace('\'', "''")
            ));
        }
    }

    stmts
}

/// Generate CREATE TYPE statements for enums (PG target only).
fn generate_enum_types(schema: &IntrospectedSchema, target_dialect: Dialect) -> Vec<String> {
    if target_dialect != Dialect::Postgres || schema.enums.is_empty() {
        return vec![];
    }

    schema
        .enums
        .iter()
        .map(|e| {
            let qname = quote_identifier(&e.name, target_dialect);
            let values: Vec<String> = e
                .values
                .iter()
                .map(|v| format!("'{}'", v.replace('\'', "''")))
                .collect();
            format!("CREATE TYPE {qname} AS ENUM ({});", values.join(", "))
        })
        .collect()
}

/// Detect circular FK dependencies among tables.
fn detect_fk_cycles(tables: &[TableInfo]) -> bool {
    use std::collections::HashSet;

    type Key<'a> = (&'a str, &'a str);

    let table_keys: HashSet<Key> = tables
        .iter()
        .map(|t| (t.schema.as_str(), t.name.as_str()))
        .collect();
    let mut visited: HashSet<Key> = HashSet::new();
    let mut in_stack: HashSet<Key> = HashSet::new();

    fn dfs<'a>(
        node: Key<'a>,
        adj: &HashMap<Key<'a>, Vec<Key<'a>>>,
        visited: &mut HashSet<Key<'a>>,
        in_stack: &mut HashSet<Key<'a>>,
    ) -> bool {
        visited.insert(node);
        in_stack.insert(node);
        if let Some(neighbors) = adj.get(&node) {
            for &neighbor in neighbors {
                if !visited.contains(&neighbor) {
                    if dfs(neighbor, adj, visited, in_stack) {
                        return true;
                    }
                } else if in_stack.contains(&neighbor) {
                    return true;
                }
            }
        }
        in_stack.remove(&node);
        false
    }

    let mut adj: HashMap<Key, Vec<Key>> = HashMap::new();
    for table in tables {
        let src = (table.schema.as_str(), table.name.as_str());
        for c in &table.constraints {
            if c.constraint_type == ConstraintType::ForeignKey {
                if let Some(ref fk) = c.foreign_key {
                    let dst = (fk.ref_schema.as_str(), fk.ref_table.as_str());
                    if table_keys.contains(&dst) && dst != src {
                        adj.entry(src).or_default().push(dst);
                    }
                }
            }
        }
    }

    for table in tables {
        let key = (table.schema.as_str(), table.name.as_str());
        if !visited.contains(&key) {
            if dfs(key, &adj, &mut visited, &mut in_stack) {
                return true;
            }
        }
    }
    false
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::testutil::{col, schema_pg, table};

    #[test]
    fn test_quote_identifier_pg() {
        assert_eq!(quote_identifier("users", Dialect::Postgres), "\"users\"");
        assert_eq!(quote_identifier("my\"table", Dialect::Postgres), "\"my\"\"table\"");
    }

    #[test]
    fn test_quote_identifier_mysql() {
        assert_eq!(quote_identifier("users", Dialect::Mysql), "`users`");
    }

    #[test]
    fn test_quote_identifier_mssql() {
        assert_eq!(quote_identifier("users", Dialect::Mssql), "[users]");
    }

    #[test]
    fn test_translate_default_now() {
        assert_eq!(translate_default_function("now()", Dialect::Mysql), "CURRENT_TIMESTAMP");
        assert_eq!(translate_default_function("GETDATE()", Dialect::Postgres), "now()");
        assert_eq!(translate_default_function("CURRENT_TIMESTAMP", Dialect::Mssql), "GETDATE()");
    }

    #[test]
    fn test_translate_default_uuid() {
        assert_eq!(translate_default_function("gen_random_uuid()", Dialect::Mysql), "(UUID())");
        assert_eq!(translate_default_function("NEWID()", Dialect::Postgres), "gen_random_uuid()");
    }

    #[test]
    fn test_generate_create_table_pg_to_mysql() {
        let t = table("users")
            .schema("")
            .column(col("id").build())
            .column(col("name").udt("varchar").max_length(100).build())
            .column(col("bio").udt("text").nullable().build())
            .pk("pk_users", &["id"])
            .build();
        let options = DdlOptions {
            target_dialect: Dialect::Mysql, split_tables: false, apply: false,
            noindexes: false, noconstraints: false, nocomments: false,
        };
        let ddl = generate_create_table(&t, Dialect::Postgres, Dialect::Mysql, &options);
        assert!(ddl.contains("CREATE TABLE `users`"), "DDL was: {ddl}");
        assert!(ddl.contains("`id` INT NOT NULL"), "DDL was: {ddl}");
        assert!(ddl.contains("`name` VARCHAR(100) NOT NULL"), "DDL was: {ddl}");
        assert!(ddl.contains("`bio` TEXT"), "DDL was: {ddl}");
        assert!(ddl.contains("PRIMARY KEY (`id`)"), "DDL was: {ddl}");
    }

    #[test]
    fn test_generate_create_table_pg_to_pg() {
        let t = table("items")
            .column(col("id").build())
            .column(col("price").udt("numeric").precision(10, 2).build())
            .pk("pk_items", &["id"])
            .build();
        let options = DdlOptions {
            target_dialect: Dialect::Postgres, split_tables: false, apply: false,
            noindexes: false, noconstraints: false, nocomments: false,
        };
        let ddl = generate_create_table(&t, Dialect::Postgres, Dialect::Postgres, &options);
        assert!(ddl.contains("\"id\" INTEGER NOT NULL"));
        assert!(ddl.contains("\"price\" NUMERIC(10, 2) NOT NULL"));
    }

    #[test]
    fn test_full_generate_single() {
        let schema = schema_pg(vec![
            table("users").schema("").column(col("id").build())
                .column(col("name").udt("varchar").max_length(100).build())
                .pk("pk_users", &["id"]).build(),
        ]);
        let options = DdlOptions {
            target_dialect: Dialect::Mysql, split_tables: false, apply: false,
            noindexes: false, noconstraints: false, nocomments: false,
        };
        let gen = DdlGenerator;
        match gen.generate(&schema, None, &options) {
            DdlOutput::Single(ddl) => {
                assert!(ddl.contains("CREATE TABLE `users`"));
                assert!(ddl.contains("Source: postgres, Target: mysql"));
            }
            DdlOutput::Split(_) => panic!("Expected single output"),
        }
    }

    #[test]
    fn test_full_generate_split() {
        let schema = schema_pg(vec![
            table("users").column(col("id").build()).pk("pk_users", &["id"]).build(),
            table("posts").column(col("id").build()).pk("pk_posts", &["id"]).build(),
        ]);
        let options = DdlOptions {
            target_dialect: Dialect::Postgres, split_tables: true, apply: false,
            noindexes: false, noconstraints: false, nocomments: false,
        };
        match DdlGenerator.generate(&schema, None, &options) {
            DdlOutput::Split(files) => {
                let names: Vec<&str> = files.iter().map(|(n, _)| n.as_str()).collect();
                assert!(names.contains(&"users.sql"));
                assert!(names.contains(&"posts.sql"));
                assert!(names.contains(&"_order.txt"));
            }
            DdlOutput::Single(_) => panic!("Expected split output"),
        }
    }

    #[test]
    fn test_boolean_default_mssql_to_pg() {
        assert_eq!(format_ddl_default_typed("((1))", Dialect::Mssql, Dialect::Postgres, true), "true");
        assert_eq!(format_ddl_default_typed("((0))", Dialect::Mssql, Dialect::Postgres, true), "false");
    }

    #[test]
    fn test_integer_default_not_converted_to_boolean() {
        assert_eq!(format_ddl_default_typed("((0))", Dialect::Mssql, Dialect::Postgres, false), "0");
        assert_eq!(format_ddl_default_typed("((1))", Dialect::Mssql, Dialect::Postgres, false), "1");
    }

    #[test]
    fn test_boolean_default_pg_to_mysql() {
        assert_eq!(format_ddl_default_typed("true", Dialect::Postgres, Dialect::Mysql, true), "1");
        assert_eq!(format_ddl_default_typed("false", Dialect::Postgres, Dialect::Mysql, true), "0");
    }

    #[test]
    fn test_boolean_default_pg_to_mssql() {
        assert_eq!(format_ddl_default_typed("true", Dialect::Postgres, Dialect::Mssql, true), "1");
        assert_eq!(format_ddl_default_typed("false", Dialect::Postgres, Dialect::Mssql, true), "0");
    }

    #[test]
    fn test_ensure_default_quoting() {
        assert_eq!(ensure_default_quoting("member"), "'member'");
        assert_eq!(ensure_default_quoting("active"), "'active'");
        assert_eq!(ensure_default_quoting("'member'"), "'member'");
        assert_eq!(ensure_default_quoting("0"), "0");
        assert_eq!(ensure_default_quoting("3.14"), "3.14");
        assert_eq!(ensure_default_quoting("NULL"), "NULL");
        assert_eq!(ensure_default_quoting("true"), "true");
        assert_eq!(ensure_default_quoting("false"), "false");
        assert_eq!(ensure_default_quoting("now()"), "now()");
        assert_eq!(ensure_default_quoting("CURRENT_TIMESTAMP"), "CURRENT_TIMESTAMP");
        assert_eq!(ensure_default_quoting("it's"), "'it''s'");
    }
}
