//! Schema diff engine for the DDL generator.
//!
//! Compares source and target `IntrospectedSchema` and emits ALTER statements
//! for new/dropped/modified tables and columns. Inspired by Alembic's autogenerate.

use std::collections::{HashMap, HashSet};

use crate::cli::DdlOptions;
use crate::codegen::topo_sort_tables;
use crate::ddl_typemap;
use crate::dialect::Dialect;
use crate::schema::{ColumnInfo, IntrospectedSchema, TableInfo, TableType};

use super::ddl::{
    format_ddl_default_typed, generate_column_def, generate_create_table, generate_indexes,
    qualified_table_name, quote_identifier,
};

/// Diff two schemas and emit ALTER statements.
/// Detects new/dropped tables and new/dropped/modified columns.
pub fn diff_schemas(
    source: &IntrospectedSchema,
    target: &IntrospectedSchema,
    options: &DdlOptions,
) -> String {
    let source_dialect = source.dialect;
    let target_dialect = options.target_dialect;

    // For MySQL, the schema is the database name. When each side has exactly
    // one schema (the common case), treat those as defaults so sourcedb.users
    // matches targetdb.users. Non-default schemas are preserved for multi-schema diffs.
    let mysql_defaults = build_mysql_defaults(source, target, source_dialect, target_dialect);

    let source_map: HashMap<(&str, &str), &TableInfo> = source
        .tables
        .iter()
        .map(|t| {
            (
                (normalize_schema(&t.schema, &mysql_defaults), t.name.as_str()),
                t,
            )
        })
        .collect();
    let target_map: HashMap<(&str, &str), &TableInfo> = target
        .tables
        .iter()
        .map(|t| {
            (
                (normalize_schema(&t.schema, &mysql_defaults), t.name.as_str()),
                t,
            )
        })
        .collect();

    let mut stmts: Vec<String> = Vec::new();

    // New tables (in source, not in target)
    let sorted_source = topo_sort_tables(&source.tables);
    for table in &sorted_source {
        if table.table_type != TableType::Table {
            continue;
        }
        let key = (
            normalize_schema(&table.schema, &mysql_defaults),
            table.name.as_str(),
        );
        if !target_map.contains_key(&key) {
            stmts.push(generate_create_table(
                table,
                source_dialect,
                target_dialect,
                options,
            ));
            if !options.noindexes {
                stmts.extend(generate_indexes(table, target_dialect));
            }
        }
    }

    // Modified tables (in both): compare columns
    for table in &sorted_source {
        if table.table_type != TableType::Table {
            continue;
        }
        let key = (
            normalize_schema(&table.schema, &mysql_defaults),
            table.name.as_str(),
        );
        if let Some(target_table) = target_map.get(&key) {
            let alters =
                diff_table_columns(table, target_table, source_dialect, target_dialect);
            stmts.extend(alters);
        }
    }

    // Dropped tables (in target, not in source)
    let mut dropped: Vec<(&str, &str)> = target_map
        .keys()
        .filter(|key| !source_map.contains_key(*key))
        .copied()
        .collect();
    dropped.sort();
    for (schema, name) in dropped {
        let qname = qualified_table_name(schema, name, target_dialect);
        stmts.push(format!(
            "-- WARNING: destructive operation\nDROP TABLE IF EXISTS {qname};"
        ));
    }

    if stmts.is_empty() {
        "-- No schema changes detected.\n".to_string()
    } else {
        let header = format!(
            "-- Generated by uvg (diff)\n-- Source: {source_dialect}, Target: {target_dialect}\n\n"
        );
        format!("{header}{}\n", stmts.join("\n\n"))
    }
}

/// Build the set of MySQL database names to treat as defaults for diff normalization.
fn build_mysql_defaults(
    source: &IntrospectedSchema,
    target: &IntrospectedSchema,
    source_dialect: Dialect,
    target_dialect: Dialect,
) -> HashSet<String> {
    let mut defaults = HashSet::new();
    if source_dialect == Dialect::Mysql {
        let schemas: HashSet<&str> = source.tables.iter().map(|t| t.schema.as_str()).collect();
        if schemas.len() == 1 {
            defaults.insert(schemas.into_iter().next().unwrap().to_string());
        }
    }
    if target_dialect == Dialect::Mysql {
        let schemas: HashSet<&str> = target.tables.iter().map(|t| t.schema.as_str()).collect();
        if schemas.len() == 1 {
            defaults.insert(schemas.into_iter().next().unwrap().to_string());
        }
    }
    defaults
}

/// Normalize default schemas to empty string for cross-dialect comparison.
/// PG "public", MSSQL "dbo", SQLite "main" are well-known defaults.
/// MySQL database names in `mysql_defaults` are also treated as defaults.
fn normalize_schema<'a>(schema: &'a str, mysql_defaults: &HashSet<String>) -> &'a str {
    if matches!(schema, "public" | "dbo" | "main" | "") {
        return "";
    }
    if mysql_defaults.contains(schema) {
        return "";
    }
    schema
}

/// Compare columns between source and target tables, emit ALTER statements.
fn diff_table_columns(
    source: &TableInfo,
    target: &TableInfo,
    source_dialect: Dialect,
    target_dialect: Dialect,
) -> Vec<String> {
    let mut stmts = Vec::new();
    let tname = qualified_table_name(&source.schema, &source.name, target_dialect);

    let source_cols: HashMap<&str, &ColumnInfo> =
        source.columns.iter().map(|c| (c.name.as_str(), c)).collect();
    let target_cols: HashMap<&str, &ColumnInfo> =
        target.columns.iter().map(|c| (c.name.as_str(), c)).collect();

    // New columns
    for col in &source.columns {
        if !target_cols.contains_key(col.name.as_str()) {
            let col_def = generate_column_def(col, &source.constraints, source_dialect, target_dialect);
            let col_def = col_def.trim();
            let add_clause = match target_dialect {
                Dialect::Mssql => "ADD",
                _ => "ADD COLUMN",
            };
            stmts.push(format!("ALTER TABLE {tname} {add_clause} {col_def};"));
        }
    }

    // Modified columns
    for col in &source.columns {
        if let Some(target_col) = target_cols.get(col.name.as_str()) {
            let alters = diff_column(
                col,
                target_col,
                &source.schema,
                &source.name,
                source_dialect,
                target_dialect,
            );
            stmts.extend(alters);
        }
    }

    // Dropped columns
    let mut dropped: Vec<&str> = target_cols
        .keys()
        .filter(|name| !source_cols.contains_key(*name))
        .copied()
        .collect();
    dropped.sort();
    for name in dropped {
        let qcol = quote_identifier(name, target_dialect);
        stmts.push(format!(
            "-- WARNING: destructive operation\nALTER TABLE {tname} DROP COLUMN {qcol};"
        ));
    }

    stmts
}

/// Compare a single column and emit ALTER statements if different.
/// Compares type, nullability, and default values.
fn diff_column(
    source: &ColumnInfo,
    target: &ColumnInfo,
    table_schema: &str,
    table_name: &str,
    source_dialect: Dialect,
    target_dialect: Dialect,
) -> Vec<String> {
    let mut stmts = Vec::new();
    let tname = qualified_table_name(table_schema, table_name, target_dialect);
    let cname = quote_identifier(&source.name, target_dialect);

    let source_type = ddl_typemap::map_ddl_type(source, source_dialect, target_dialect);
    let target_type = ddl_typemap::map_ddl_type(target, target_dialect, target_dialect);

    let type_changed = source_type.sql_type != target_type.sql_type;
    let nullable_changed = source.is_nullable != target.is_nullable;

    // Compare defaults with boolean-aware normalization
    let canonical = ddl_typemap::to_canonical(source, source_dialect);
    let is_boolean = matches!(canonical, ddl_typemap::CanonicalType::Boolean);
    let source_default = source
        .column_default
        .as_deref()
        .map(|d| format_ddl_default_typed(d, source_dialect, target_dialect, is_boolean));
    let target_default = target
        .column_default
        .as_deref()
        .map(|d| format_ddl_default_typed(d, target_dialect, target_dialect, is_boolean));
    let default_changed = source_default != target_default;

    if !type_changed && !nullable_changed && !default_changed {
        return stmts;
    }

    match target_dialect {
        Dialect::Postgres => {
            if type_changed {
                stmts.push(format!(
                    "ALTER TABLE {tname} ALTER COLUMN {cname} TYPE {};",
                    source_type.sql_type
                ));
            }
            if nullable_changed {
                if source.is_nullable {
                    stmts.push(format!(
                        "ALTER TABLE {tname} ALTER COLUMN {cname} DROP NOT NULL;"
                    ));
                } else {
                    stmts.push(format!(
                        "ALTER TABLE {tname} ALTER COLUMN {cname} SET NOT NULL;"
                    ));
                }
            }
            if default_changed {
                match &source_default {
                    Some(d) => stmts.push(format!(
                        "ALTER TABLE {tname} ALTER COLUMN {cname} SET DEFAULT {d};"
                    )),
                    None => stmts.push(format!(
                        "ALTER TABLE {tname} ALTER COLUMN {cname} DROP DEFAULT;"
                    )),
                }
            }
        }
        Dialect::Mysql => {
            let not_null = if !source.is_nullable { " NOT NULL" } else { "" };
            let default_clause = match &source_default {
                Some(d) => format!(" DEFAULT {d}"),
                None => String::new(),
            };
            stmts.push(format!(
                "ALTER TABLE {tname} MODIFY COLUMN {cname} {}{not_null}{default_clause};",
                source_type.sql_type
            ));
        }
        Dialect::Mssql => {
            if type_changed || nullable_changed {
                let not_null = if !source.is_nullable { " NOT NULL" } else { " NULL" };
                stmts.push(format!(
                    "ALTER TABLE {tname} ALTER COLUMN {cname} {}{not_null};",
                    source_type.sql_type
                ));
            }
            if default_changed {
                stmts.push(format!(
                    "-- NOTE: MSSQL requires dropping the named default constraint first.\n-- Run: SELECT name FROM sys.default_constraints WHERE parent_object_id = OBJECT_ID('{tname_raw}') AND col_name(parent_object_id, parent_column_id) = '{col_name}'\n-- Then: ALTER TABLE {tname} DROP CONSTRAINT <name>;",
                    tname_raw = table_name,
                    col_name = source.name
                ));
                if let Some(ref d) = source_default {
                    stmts.push(format!(
                        "ALTER TABLE {tname} ADD DEFAULT {d} FOR {cname};"
                    ));
                }
            }
        }
        Dialect::Sqlite => {
            stmts.push(format!(
                "-- WARNING: SQLite does not support ALTER COLUMN. Table recreation required.\n-- ALTER TABLE {tname} ALTER COLUMN {cname} TYPE {};",
                source_type.sql_type
            ));
        }
    }

    stmts
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::cli::DdlOptions;
    use crate::testutil::{col, schema_pg, table};

    fn default_options(target: Dialect) -> DdlOptions {
        DdlOptions {
            target_dialect: target,
            split_tables: false,
            apply: false,
            noindexes: false,
            noconstraints: false,
            nocomments: false,
        }
    }

    #[test]
    fn test_diff_new_table() {
        let source = schema_pg(vec![
            table("users").column(col("id").build()).pk("pk", &["id"]).build(),
        ]);
        let target = schema_pg(vec![]);
        let ddl = diff_schemas(&source, &target, &default_options(Dialect::Postgres));
        assert!(ddl.contains("CREATE TABLE \"users\""));
    }

    #[test]
    fn test_diff_dropped_table() {
        let source = schema_pg(vec![]);
        let target = schema_pg(vec![
            table("old").column(col("id").build()).pk("pk", &["id"]).build(),
        ]);
        let ddl = diff_schemas(&source, &target, &default_options(Dialect::Postgres));
        assert!(ddl.contains("DROP TABLE IF EXISTS"));
        assert!(ddl.contains("WARNING: destructive"));
    }

    #[test]
    fn test_diff_new_column() {
        let source = schema_pg(vec![
            table("users")
                .column(col("id").build())
                .column(col("email").udt("varchar").max_length(255).build())
                .pk("pk", &["id"])
                .build(),
        ]);
        let target = schema_pg(vec![
            table("users").column(col("id").build()).pk("pk", &["id"]).build(),
        ]);
        let ddl = diff_schemas(&source, &target, &default_options(Dialect::Postgres));
        assert!(ddl.contains("ADD COLUMN \"email\" VARCHAR(255) NOT NULL"));
    }

    #[test]
    fn test_diff_no_changes() {
        let schema = schema_pg(vec![
            table("users").column(col("id").build()).pk("pk", &["id"]).build(),
        ]);
        let ddl = diff_schemas(&schema, &schema, &default_options(Dialect::Postgres));
        assert!(ddl.contains("No schema changes detected"));
    }

    #[test]
    fn test_diff_cross_dialect_default_schemas_match() {
        let source = schema_pg(vec![
            table("users").column(col("id").build()).pk("pk", &["id"]).build(),
        ]);
        let target = schema_pg(vec![
            table("users").schema("dbo").column(col("id").build()).pk("pk", &["id"]).build(),
        ]);
        let ddl = diff_schemas(&source, &target, &default_options(Dialect::Postgres));
        assert!(ddl.contains("No schema changes detected"), "public should match dbo: {ddl}");
    }

    #[test]
    fn test_diff_multi_schema_preserved() {
        let source = schema_pg(vec![
            table("users").schema("schema_a").column(col("id").build()).pk("pk", &["id"]).build(),
        ]);
        let target = schema_pg(vec![
            table("users").schema("schema_b").column(col("id").build()).pk("pk", &["id"]).build(),
        ]);
        let ddl = diff_schemas(&source, &target, &default_options(Dialect::Postgres));
        assert!(
            ddl.contains("CREATE TABLE") && ddl.contains("DROP TABLE"),
            "Non-default schemas should not match: {ddl}"
        );
    }
}
