-- ============================================================
-- crm_postgres.sql — 3NF CRM source schema, native PostgreSQL idioms
--
-- Engine-specific features exercised (for SMT migration testing):
--   * GENERATED BY DEFAULT AS IDENTITY (SQL-standard form, PG 10+)
--   * BIGINT GENERATED BY DEFAULT AS IDENTITY for audit log
--   * TIMESTAMPTZ (timezone-aware)
--   * UUID + gen_random_uuid()  (PG 13+ has it without pgcrypto)
--   * TEXT (no length cap)
--   * JSONB columns
--   * TEXT[] array columns
--   * BOOLEAN
--   * GENERATED ALWAYS AS (expression) STORED computed columns
--   * CHECK constraints with regex (~)
--   * Composite PK and composite FK to composite PK
--   * Self-referencing FKs
--   * CASCADE / SET NULL / NO ACTION mix
-- ============================================================

CREATE TABLE companies (
    id            INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code          VARCHAR(20)   NOT NULL UNIQUE,
    name          TEXT          NOT NULL,
    industry      VARCHAR(50),
    founded_date  DATE,
    settings      JSONB         NOT NULL DEFAULT '{}'::jsonb,
    is_active     BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_companies_code_upper CHECK (code = UPPER(code))
);

CREATE TABLE departments (
    id            INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id    INTEGER       NOT NULL REFERENCES companies(id),
    parent_id     INTEGER       REFERENCES departments(id),
    name          TEXT          NOT NULL,
    code          VARCHAR(20)   NOT NULL,
    cost_center   VARCHAR(20),
    is_active     BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_dept_code      UNIQUE (company_id, code),
    CONSTRAINT chk_dept_code_up  CHECK (code = UPPER(code))
);

CREATE TABLE employees (
    id                INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id        INTEGER       NOT NULL REFERENCES companies(id),
    department_id     INTEGER       REFERENCES departments(id),
    manager_id        INTEGER       REFERENCES employees(id),
    employee_uuid     UUID          NOT NULL DEFAULT gen_random_uuid(),
    employee_no       VARCHAR(20)   NOT NULL,
    first_name        TEXT          NOT NULL,
    last_name         TEXT          NOT NULL,
    full_name         TEXT          GENERATED ALWAYS AS (first_name || ' ' || last_name) STORED,
    email             VARCHAR(255)  NOT NULL,
    phone             VARCHAR(50),
    job_title         TEXT,
    salary            NUMERIC(12,2),
    hire_date         TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    termination_date  TIMESTAMPTZ,
    skills            TEXT[]        NOT NULL DEFAULT '{}',
    profile           JSONB         NOT NULL DEFAULT '{}'::jsonb,
    is_active         BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at        TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_emp_no       UNIQUE (company_id, employee_no),
    CONSTRAINT uq_emp_email    UNIQUE (email),
    CONSTRAINT uq_emp_uuid     UNIQUE (employee_uuid),
    CONSTRAINT chk_emp_email   CHECK (email ~ '^[^@\s]+@[^@\s]+\.[^@\s]+$'),
    CONSTRAINT chk_emp_salary  CHECK (salary IS NULL OR salary >= 0),
    CONSTRAINT chk_emp_term    CHECK (termination_date IS NULL OR termination_date >= hire_date)
);

CREATE TABLE customers (
    id                    INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id            INTEGER       NOT NULL REFERENCES companies(id),
    external_id           UUID          NOT NULL DEFAULT gen_random_uuid(),
    customer_code         VARCHAR(20)   NOT NULL,
    customer_type         VARCHAR(20)   NOT NULL DEFAULT 'individual',
    company_name          TEXT,
    first_name            TEXT,
    last_name             TEXT,
    email                 VARCHAR(255)  NOT NULL,
    phone                 VARCHAR(50),
    fax                   VARCHAR(50),
    website               VARCHAR(500),
    tax_id                VARCHAR(50),
    credit_limit          NUMERIC(15,2) NOT NULL DEFAULT 0,
    notes                 TEXT,
    metadata              JSONB         NOT NULL DEFAULT '{}'::jsonb,
    assigned_employee_id  INTEGER       REFERENCES employees(id) ON DELETE SET NULL,
    is_active             BOOLEAN       NOT NULL DEFAULT TRUE,
    is_deleted            BOOLEAN       NOT NULL DEFAULT FALSE,
    deleted_at            TIMESTAMPTZ,
    created_at            TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at            TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_cust_code      UNIQUE (company_id, customer_code),
    CONSTRAINT uq_cust_external  UNIQUE (external_id),
    CONSTRAINT uq_cust_email     UNIQUE (email),
    CONSTRAINT chk_cust_type     CHECK (customer_type IN ('individual','company','government')),
    CONSTRAINT chk_cust_credit   CHECK (credit_limit >= 0),
    CONSTRAINT chk_cust_email    CHECK (email ~ '^[^@\s]+@[^@\s]+\.[^@\s]+$'),
    CONSTRAINT chk_cust_identity CHECK (
        (customer_type = 'individual' AND first_name IS NOT NULL AND last_name IS NOT NULL)
     OR (customer_type IN ('company','government') AND company_name IS NOT NULL)
    )
);

CREATE TABLE customer_addresses (
    id              INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id     INTEGER       NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
    address_type    VARCHAR(20)   NOT NULL,
    line1           TEXT          NOT NULL,
    line2           TEXT,
    city            TEXT          NOT NULL,
    state_province  TEXT,
    postal_code     VARCHAR(20),
    country_code    CHAR(2)       NOT NULL,
    is_primary      BOOLEAN       NOT NULL DEFAULT FALSE,
    CONSTRAINT chk_addr_type     CHECK (address_type IN ('billing','shipping','physical','mailing')),
    CONSTRAINT chk_addr_country  CHECK (country_code = UPPER(country_code))
);

CREATE TABLE contacts (
    id           INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id  INTEGER       NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
    first_name   TEXT          NOT NULL,
    last_name    TEXT          NOT NULL,
    title        TEXT,
    email        VARCHAR(255),
    phone        VARCHAR(50),
    is_primary   BOOLEAN       NOT NULL DEFAULT FALSE,
    is_active    BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at   TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE product_categories (
    id          INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id   INTEGER       REFERENCES product_categories(id),
    name        TEXT          NOT NULL,
    slug        VARCHAR(100)  NOT NULL UNIQUE,
    sort_order  INTEGER       NOT NULL DEFAULT 0,
    is_active   BOOLEAN       NOT NULL DEFAULT TRUE,
    CONSTRAINT chk_pcat_slug_lo CHECK (slug = LOWER(slug))
);

CREATE TABLE products (
    id            INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id   INTEGER       REFERENCES product_categories(id),
    sku           VARCHAR(50)   NOT NULL UNIQUE,
    name          TEXT          NOT NULL,
    description   TEXT,
    unit_price    NUMERIC(12,2) NOT NULL,
    cost_price    NUMERIC(12,2),
    currency      CHAR(3)       NOT NULL DEFAULT 'USD',
    weight_grams  INTEGER,
    margin        NUMERIC(8,4)  GENERATED ALWAYS AS (
        CASE WHEN cost_price IS NULL OR cost_price = 0 THEN NULL
             ELSE (unit_price - cost_price) / cost_price END
    ) STORED,
    tags          TEXT[]        NOT NULL DEFAULT '{}',
    attributes    JSONB         NOT NULL DEFAULT '{}'::jsonb,
    is_taxable    BOOLEAN       NOT NULL DEFAULT TRUE,
    is_active     BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_prod_price    CHECK (unit_price >= 0),
    CONSTRAINT chk_prod_cost     CHECK (cost_price IS NULL OR cost_price >= 0),
    CONSTRAINT chk_prod_currency CHECK (currency = UPPER(currency)),
    CONSTRAINT chk_prod_weight   CHECK (weight_grams IS NULL OR weight_grams > 0)
);

CREATE TABLE orders (
    id             INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id     INTEGER       NOT NULL REFERENCES companies(id),
    customer_id    INTEGER       NOT NULL REFERENCES customers(id),
    order_no       VARCHAR(30)   NOT NULL,
    order_date     TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    required_date  TIMESTAMPTZ,
    shipped_at     TIMESTAMPTZ,
    subtotal       NUMERIC(15,2) NOT NULL DEFAULT 0,
    tax_amount     NUMERIC(15,2) NOT NULL DEFAULT 0,
    total_amount   NUMERIC(15,2) NOT NULL DEFAULT 0,
    currency       CHAR(3)       NOT NULL DEFAULT 'USD',
    status         VARCHAR(20)   NOT NULL DEFAULT 'pending',
    sales_rep_id   INTEGER       REFERENCES employees(id) ON DELETE SET NULL,
    notes          TEXT,
    metadata       JSONB         NOT NULL DEFAULT '{}'::jsonb,
    created_at     TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_order_no       UNIQUE (company_id, order_no),
    CONSTRAINT chk_order_required CHECK (required_date IS NULL OR required_date >= order_date),
    CONSTRAINT chk_order_amounts  CHECK (subtotal >= 0 AND tax_amount >= 0 AND total_amount >= 0),
    CONSTRAINT chk_order_total    CHECK (total_amount = subtotal + tax_amount),
    CONSTRAINT chk_order_status   CHECK (status IN ('pending','paid','shipped','delivered','cancelled')),
    CONSTRAINT chk_order_curr     CHECK (currency = UPPER(currency))
);

CREATE TABLE order_items (
    order_id      INTEGER       NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    line_no       INTEGER       NOT NULL,
    product_id    INTEGER       NOT NULL REFERENCES products(id),
    quantity      NUMERIC(10,3) NOT NULL,
    unit_price    NUMERIC(12,2) NOT NULL,
    discount_pct  NUMERIC(5,2)  NOT NULL DEFAULT 0,
    line_total    NUMERIC(15,2) GENERATED ALWAYS AS (quantity * unit_price * (1 - discount_pct / 100)) STORED,
    CONSTRAINT pk_order_items PRIMARY KEY (order_id, line_no),
    CONSTRAINT chk_oi_qty     CHECK (quantity > 0),
    CONSTRAINT chk_oi_price   CHECK (unit_price >= 0),
    CONSTRAINT chk_oi_disc    CHECK (discount_pct BETWEEN 0 AND 100)
);

CREATE TABLE invoices (
    id            INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id      INTEGER       NOT NULL REFERENCES orders(id),
    invoice_no    VARCHAR(30)   NOT NULL UNIQUE,
    issue_date    DATE          NOT NULL,
    due_date      DATE          NOT NULL,
    subtotal      NUMERIC(15,2) NOT NULL,
    tax_amount    NUMERIC(15,2) NOT NULL,
    total_amount  NUMERIC(15,2) NOT NULL,
    currency      CHAR(3)       NOT NULL DEFAULT 'USD',
    status        VARCHAR(20)   NOT NULL DEFAULT 'draft',
    sent_at       TIMESTAMPTZ,
    paid_at       TIMESTAMPTZ,
    notes         TEXT,
    created_at    TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_inv_due    CHECK (due_date >= issue_date),
    CONSTRAINT chk_inv_amts   CHECK (subtotal >= 0 AND tax_amount >= 0 AND total_amount >= 0),
    CONSTRAINT chk_inv_total  CHECK (total_amount = subtotal + tax_amount),
    CONSTRAINT chk_inv_status CHECK (status IN ('draft','sent','paid','overdue','void')),
    CONSTRAINT chk_inv_curr   CHECK (currency = UPPER(currency))
);

CREATE TABLE payments (
    id            INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id    INTEGER       NOT NULL REFERENCES invoices(id),
    amount        NUMERIC(15,2) NOT NULL,
    currency      CHAR(3)       NOT NULL DEFAULT 'USD',
    method        VARCHAR(20)   NOT NULL,
    reference_no  VARCHAR(100),
    paid_at       TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    notes         TEXT,
    CONSTRAINT chk_pay_amount  CHECK (amount > 0),
    CONSTRAINT chk_pay_method  CHECK (method IN ('card','ach','wire','check','cash','crypto')),
    CONSTRAINT chk_pay_curr    CHECK (currency = UPPER(currency))
);

CREATE TABLE tags (
    id          INTEGER     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id  INTEGER     NOT NULL REFERENCES companies(id),
    name        VARCHAR(50) NOT NULL,
    color       CHAR(7),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_tag_name  UNIQUE (company_id, name),
    CONSTRAINT chk_tag_color CHECK (color IS NULL OR color ~ '^#[0-9A-Fa-f]{6}$')
);

CREATE TABLE customer_tags (
    customer_id            INTEGER     NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
    tag_id                 INTEGER     NOT NULL REFERENCES tags(id)      ON DELETE CASCADE,
    tagged_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    tagged_by_employee_id  INTEGER     REFERENCES employees(id),
    CONSTRAINT pk_customer_tags PRIMARY KEY (customer_id, tag_id)
);
