use anyhow::Result;

use crate::cli::{ConnectionConfig, GeneratorOptions};
use crate::introspect;
use crate::schema::IntrospectedSchema;

/// Introspect a database given a ConnectionConfig.
pub(crate) async fn introspect_with_config(
    config: ConnectionConfig,
    schemas: &[String],
    table_filter: &[String],
    noviews: bool,
    options: &GeneratorOptions,
) -> Result<IntrospectedSchema> {
    match config {
        ConnectionConfig::Postgres(url) => {
            let pool = sqlx::postgres::PgPoolOptions::new()
                .max_connections(1)
                .connect(&url)
                .await?;
            let s = introspect::pg::introspect(&pool, schemas, table_filter, noviews, options).await;
            pool.close().await;
            Ok(s?)
        }
        ConnectionConfig::Mssql {
            host,
            port,
            database,
            user,
            password,
            trust_cert,
        } => {
            let mut client =
                introspect::mssql::connect(&host, port, &database, &user, &password, trust_cert)
                    .await?;
            Ok(
                introspect::mssql::introspect(
                    &mut client,
                    schemas,
                    table_filter,
                    noviews,
                    options,
                )
                .await?,
            )
        }
        ConnectionConfig::Mysql(url) => {
            let pool = sqlx::mysql::MySqlPoolOptions::new()
                .max_connections(1)
                .connect(&url)
                .await?;
            let s =
                introspect::mysql::introspect(&pool, schemas, table_filter, noviews, options).await;
            pool.close().await;
            Ok(s?)
        }
        ConnectionConfig::Sqlite(url) => {
            let pool = sqlx::sqlite::SqlitePoolOptions::new()
                .max_connections(1)
                .connect(&url)
                .await?;
            let s = introspect::sqlite::introspect(&pool, table_filter, noviews, options).await;
            pool.close().await;
            Ok(s?)
        }
    }
}

/// Result of executing a single DDL statement.
pub(crate) struct StmtResult {
    pub sql: String,
    pub error: Option<String>,
}

/// Split DDL output into individual statements.
/// Strips leading comment-only lines from each chunk so that header comments
/// (e.g. "-- Generated by uvg") don't prevent execution, but preserves
/// inline comments like "-- WARNING: destructive operation" preceding a statement.
fn split_statements(ddl: &str) -> Vec<String> {
    ddl.split(';')
        .map(|s| s.trim())
        .filter(|s| !s.is_empty())
        .filter_map(|s| {
            // Strip leading comment-only lines to get to the actual SQL
            let stripped: String = s
                .lines()
                .skip_while(|line| {
                    let t = line.trim();
                    t.is_empty() || t.starts_with("--")
                })
                .collect::<Vec<_>>()
                .join("\n");
            if stripped.is_empty() {
                None
            } else {
                Some(stripped)
            }
        })
        .collect()
}

/// Execute DDL statements one-by-one against the target database.
/// Stops on first error.
pub(crate) async fn execute_ddl(config: &ConnectionConfig, ddl: &str) -> Result<Vec<StmtResult>> {
    let statements = split_statements(ddl);
    let mut results = Vec::new();

    match config {
        ConnectionConfig::Postgres(url) => {
            let pool = sqlx::postgres::PgPoolOptions::new()
                .max_connections(1)
                .connect(url)
                .await?;
            for stmt in &statements {
                let r = sqlx::query(stmt).execute(&pool).await;
                let error = r.err().map(|e| e.to_string());
                let failed = error.is_some();
                results.push(StmtResult {
                    sql: stmt.to_string(),
                    error,
                });
                if failed {
                    break;
                }
            }
            pool.close().await;
        }
        ConnectionConfig::Mysql(url) => {
            let pool = sqlx::mysql::MySqlPoolOptions::new()
                .max_connections(1)
                .connect(url)
                .await?;
            for stmt in &statements {
                let r = sqlx::query(stmt).execute(&pool).await;
                let error = r.err().map(|e| e.to_string());
                let failed = error.is_some();
                results.push(StmtResult {
                    sql: stmt.to_string(),
                    error,
                });
                if failed {
                    break;
                }
            }
            pool.close().await;
        }
        ConnectionConfig::Sqlite(url) => {
            let pool = sqlx::sqlite::SqlitePoolOptions::new()
                .max_connections(1)
                .connect(url)
                .await?;
            for stmt in &statements {
                let r = sqlx::query(stmt).execute(&pool).await;
                let error = r.err().map(|e| e.to_string());
                let failed = error.is_some();
                results.push(StmtResult {
                    sql: stmt.to_string(),
                    error,
                });
                if failed {
                    break;
                }
            }
            pool.close().await;
        }
        ConnectionConfig::Mssql {
            host,
            port,
            database,
            user,
            password,
            trust_cert,
        } => {
            let mut client =
                introspect::mssql::connect(host, *port, database, user, password, *trust_cert)
                    .await?;
            for stmt in &statements {
                let r = client.execute(stmt.to_string(), &[]).await;
                let error = r.err().map(|e| e.to_string());
                let failed = error.is_some();
                results.push(StmtResult {
                    sql: stmt.to_string(),
                    error,
                });
                if failed {
                    break;
                }
            }
        }
    }

    Ok(results)
}
