use std::fs::{self, OpenOptions};
use std::io::Write;
use std::path::{Path, PathBuf};

use anyhow::{anyhow, Context, Result};

use crate::cli::InitCommand;

const BASELINE_REVISION: &str = "00000000_000000";
const BASELINE_DESCRIPTION: &str = "initial baseline";
const BASELINE_FILENAME: &str = ".uvg-revision-00000000_000000_initial.sql";
const META_FILENAME: &str = "meta.yaml";

#[derive(Debug, Default, PartialEq, Eq)]
pub(crate) struct InitReport {
    pub created: Vec<PathBuf>,
    pub existing: Vec<PathBuf>,
}

impl InitReport {
    fn record(&mut self, result: CreateResult) {
        match result {
            CreateResult::Created(path) => self.created.push(path),
            CreateResult::Existing(path) => self.existing.push(path),
        }
    }
}

enum CreateResult {
    Created(PathBuf),
    Existing(PathBuf),
}

pub(crate) fn run(args: &InitCommand) -> Result<()> {
    let report = init_project(args)?;
    print_report(&report);
    Ok(())
}

pub(crate) fn init_project(args: &InitCommand) -> Result<InitReport> {
    let mut report = InitReport::default();

    report.record(create_dir_if_missing(&args.migrations_dir)?);
    report.record(create_file_if_missing(
        &args.migrations_dir.join(BASELINE_FILENAME),
        baseline_sql().as_bytes(),
    )?);
    report.record(create_file_if_missing(
        &args.migrations_dir.join(META_FILENAME),
        meta_yaml().as_bytes(),
    )?);
    report.record(create_file_if_missing(
        &args.config,
        config_toml(&args.migrations_dir).as_bytes(),
    )?);

    Ok(report)
}

fn create_dir_if_missing(path: &Path) -> Result<CreateResult> {
    if path.exists() {
        if path.is_dir() {
            return Ok(CreateResult::Existing(path.to_path_buf()));
        }
        return Err(anyhow!(
            "uvg init cannot create {}: a non-directory already exists there",
            path.display()
        ));
    }

    fs::create_dir_all(path).with_context(|| format!("failed to create {}", path.display()))?;
    Ok(CreateResult::Created(path.to_path_buf()))
}

fn create_file_if_missing(path: &Path, body: &[u8]) -> Result<CreateResult> {
    if path.exists() {
        return Ok(CreateResult::Existing(path.to_path_buf()));
    }
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)
            .with_context(|| format!("failed to create {}", parent.display()))?;
    }
    let mut file = OpenOptions::new()
        .write(true)
        .create_new(true)
        .open(path)
        .with_context(|| format!("failed to create {}", path.display()))?;
    file.write_all(body)
        .with_context(|| format!("failed to write {}", path.display()))?;
    Ok(CreateResult::Created(path.to_path_buf()))
}

fn print_report(report: &InitReport) {
    if !report.created.is_empty() {
        eprintln!("Created:");
        for path in &report.created {
            eprintln!("  {}", path.display());
        }
    }
    for path in &report.existing {
        eprintln!(
            "uvg: leaving existing artifact untouched: {}",
            path.display()
        );
    }
    eprintln!("Next steps:");
    eprintln!("  - Edit the config file to set source/target URLs.");
    eprintln!("  - Run `uvg revision <src> <tgt> --message <name>`.");
}

fn baseline_sql() -> String {
    format!(
        "-- uvg revision: {BASELINE_REVISION}\n\
         -- parent: \n\
         -- description: {BASELINE_DESCRIPTION}\n\n\
         -- UP\n\
         -- Baseline revision. No SQL is executed.\n\n\
         -- DOWN\n\
         -- Baseline downgrade. No SQL is executed.\n"
    )
}

fn meta_yaml() -> String {
    format!(
        "# Generated by uvg. Revision files are the source of truth.\n\
head: '{BASELINE_REVISION}'\n\
revisions:\n\
  - revision: '{BASELINE_REVISION}'\n\
    parent: ''\n\
    description: '{BASELINE_DESCRIPTION}'\n"
    )
}

fn config_toml(migrations_dir: &Path) -> String {
    let dir = migrations_dir.to_string_lossy();
    format!(
        "[migrations]\n\
         directory = \"{dir}\"\n\
         version_table = \"uvg_version\"\n\
         version_schema = \"\"\n\n\
         [default-profile]\n\
         source = \"postgresql://localhost/dev\"\n\
         target = \"postgresql://localhost/staging\"\n"
    )
}

#[cfg(test)]
#[path = "init_tests.rs"]
mod tests;
